In [1]:
import pandas as pd
import numpy as np
from LLM import Clasificador
from tqdm import tqdm

c:\Users\chris\Data_science\Proyectos_perso\LLMzCor.github.io\env_PAC\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [62]:
file_path = r"C:\Users\chris\Data_science\Proyectos_perso\LLMzCor.github.io\DBs\Clostridium_difficile.xlsx"
sheet = "test"
usecols= [
    'PMID',
    'Title',
    'Abstract',
    '1) Antimicrobial Resistance stain',
    '2) New treatment',
    '3) Immunization',
    'Human_summary'
]
df = pd.read_excel(
    io=file_path,
    sheet_name=sheet,
    usecols=usecols,
    index_col=0
)

In [67]:
clasificador=Clasificador()

In [10]:
f=df["2) New treatment"] == "No"
df.loc[f,"2) New treatment"]=0

In [11]:
f=df["2) New treatment"] == "Yes"
df.loc[f,"2) New treatment"]=1

In [13]:
f=df["1) Antimicrobial Resistance stain"] == "No"
df.loc[f,"1) Antimicrobial Resistance stain"]=0

In [14]:
f=df["1) Antimicrobial Resistance stain"] == "Yes"
df.loc[f,"1) Antimicrobial Resistance stain"]=1

In [68]:
df

,Title,Abstract,1) Antimicrobial Resistance stain,2) New treatment,3) Immunization,Human_summary
PMID,,,,,,
36466927,Neutralizing epitopes on Clostridioides diffic...,Toxin A (TcdA) and toxin B (TcdB) are two key ...,No,Yes,No,Using antibodies (VHHs) AH3 and AA6 are two po...
36439832,Peroxisome proliferator-activated receptor-γ a...,Clostridioides difficile is a major causative ...,No,Yes,No,"Administration of the PPAR-γ agonist, pioglita..."
36439215,The impact of dietary fibers on Clostridioides...,Diets rich in fiber may provide health benefit...,No,Yes,No,Use Inulin or pectin as a dietary-based therap...
36312948,Receptor binding protein of prophage reversibl...,Receptor-binding proteins (RBPs) are located a...,No,Yes,No,The paper studied a protein named PtsHN10M tha...
35042668,The emergence of Clostridioides difficile PCR ...,Background: Several studies have highlighted t...,Yes,No,No,This study focused on analyzing Clostridioides...
36093337,Antibiotic resistance and genomic features of ...,Background: Clostridioides difficile infection...,Yes,No,No,While current main treatments remain effective...
36026500,Characterization of the virulence of three nov...,Clostridioides (Clostridium) difficile infecti...,Yes,No,No,This study explored the emergence of novel Clo...
35939437,Discovery of a novel natural product inhibitor...,Clostridioides (Clostridium) difficile infecti...,Yes,No,No,This study was conducted in Brazil to better u...
33958010,Associations of facility-level antibiotic use ...,Previously reported associations between hospi...,Yes,No,No,This study reanalyzed the link between hospita...
35942219,Isobavachalcone From Cullen corylifolium Prese...,Background: Clostridium difficile infection (C...,No,Yes,No,This Study explored whether a traditional Chi...
35873420,Infant Formula With a Specific Blend of Five H...,Background: Human milk oligosaccharides (HMOs)...,No,No,Yes,Study whether infant formula supplemented with...
35844586,Corrigendum: Immunoinformatics approach toward...,"This corrects the article ""Immunoinformatics A...",No,No,No,"This corrects the article ""Immunoinformatics A..."
35217192,Clostridioides difficile from Brazilian hospit...,Clostridioides difficile (CD) is the most freq...,Yes,No,No,This study aimed to better understand non-toxi...
35125203,Clostridioides (Clostridium) difficile isolate...,Less is understood about the epidemiology of C...,Yes,No,No,This study provides a baseline for paediatric ...
34085620,Laboratory-identified vancomycin-resistant ent...,Background: We analyzed 2017 healthcare facili...,Yes,No,No,This study provides a baseline for paediatric ...
35677311,"Black Seed Oil, Bentonite Clay, and Probiotics...",There has been a rise in antibiotic resistance...,No,Yes,No,This case highlights the potential of compleme...
35720363,Immunoinformatics Approach Toward the Introduc...,Clostridium difficile (C.difficile) is an excl...,No,No,Yes,This in silico-designed vaccine could offer pr...
35078721,Rare toxin A-negative and toxin B-positive str...,Introduction: Clostridioides difficile (C. dif...,Yes,No,No,"This strain produces only toxin B, and such at..."
35469152,Novel structural insights for a pair of monocl...,Clostridium difficile toxins are the primary c...,No,Yes,No,The combination of B1 and B2 offers a promisin...
35104667,Linkage study of surveillance and hospital adm...,Objectives: Increasing incidence rates of Clos...,Yes,No,No,"CDI remains common in Western Australia, with ..."
35175750,"Design, Synthesis, and Characterization of TNP...","TNP-2198, a stable conjugate of a rifamycin ph...",No,Yes,No,This study introduces a novel antibacterial ag...
35360652,Molecular Epidemiology and Antimicrobial Resis...,Clostridioides difficile is a global public he...,Yes,No,No,This study reveals high genetic and toxin prof...
35252669,"Development of 1,2,4-Oxadiazole Antimicrobial ...",Colonization of the gastrointestinal (GI) trac...,No,Yes,No,"26a an analogue from 1,2,4-oxadiazole could se..."
34875405,Safety and Efficacy of Prophylactic Levofloxac...,Levofloxacin has been widely used for bacterem...,No,Yes,No,Levofloxacin prophylaxis during the peritrans...
35283831,Antigen-Specific vs. Neutralizing Antibodies A...,The immunological response against Clostridioi...,No,No,Yes,This study investigated the immune response in...
35107319,A Novel Bacteriophage with Broad Host Range ag...,Bacteriophages represent a promising option fo...,No,Yes,No,This study focuses on developing bacteriophage...
34612703,Evaluation of Piperacillin-Tazobactam for Anti...,Background: Broad-spectrum antibiotic agents a...,No,Yes,No,Piperacillin-tazobactam (PT) did not improve i...
35090351,Bezlotoxumab for Prevention of Recurrent Clost...,Objectives: Approximately 25% of patients with...,No,Yes,No,"Bezlotoxumab, a monoclonal antibody against C...."
35095921,Use of a Clostridioides difficile Murine Immun...,Adjuvant combinations may enhance or broaden t...,No,No,Yes,This study tested whether combining vaccine ad...
35016207,Emergence of Clinical Clostridioides difficile...,Background: Clostridioides difficile infection...,Yes,No,No,This study investigated if there are Vancomyci...
34991700,Myxopyronin B inhibits growth of a Fidaxomicin...,"The anaerobic, gastrointestinal pathogen Clost...",No,Yes,No,"This study evaluated the natural antibiotic, M..."
34107037,Genomic Analysis of Clostridioides difficile i...,Background: The distribution of Clostridioides...,Yes,No,No,This study examined the genetic diversity and ...
36045589,Bezlotoxumab prevents extraintestinal organ da...,Clostridioides difficile is the most common ca...,No,Yes,No,C. difficile toxins can cause systemic immune ...
35157277,Facile Affinity Maturation of Single-Domain An...,Binding affinity is one of the primary determi...,No,Yes,No,This study presents a fast and simple method t...
35036247,Microbiota diversity and bacterial load after ...,"In this letter, an experimental therapy in fou...",No,Yes,No,This scientific letter describes an experiment...
35008521,Specific Inhibition of VanZ-Mediated Resistanc...,Teicoplanin is a natural lipoglycopeptide anti...,Yes,Yes,No,This study investigated how certain bacteria—i...
34837818,"Studies on the Importance of the 7α-, and 12α-...",Chenodeoxycholic acid (CDCA) is a natural germ...,No,Yes,No,This study aimed to develop new inhibitors of ...
34955836,Soluble Non-Starch Polysaccharides From Planta...,Clostridioides difficile infection (CDI) is a ...,No,Yes,No,This study examined how soluble dietary fiber ...
34790963,Evaluation of Prolonged Versus Continuous Infu...,"Background: In 2017, a national drug shortage ...",No,Yes,No,This study evaluated continuous infusion of pi...
34775130,Real-world clinical outcomes of meropenem/vabo...,Objectives: Real-world data regarding the effe...,Yes,Yes,No,This case series reports real-world outcomes o...
33682630,New ribotype Clostridioides difficile from ST1...,Clostridioides difficile is the predominant an...,Yes,No,No,This study compared Clostridioides difficile R...
34835068,"Impact of Phage CDHS-1 on the Transcription, P...",All known Clostridioides difficile phages enco...,No,Yes,No,This study examined how the phage CDHS-1 infec...
34023223,Retrospective study of the efficacy and safety...,Introduction: According to the Japanese guidel...,No,Yes,No,This study evaluated whether Japanese guidelin...
36168487,Initial vancomycin versus metronidazole for th...,Objective: Clostridioides difficile infection ...,No,Yes,No,This study compared initial treatment with van...
34097471,The Murine Neonatal Fc Receptor Is Required fo...,The pathology associated with Clostridioides d...,No,No,No,This study investigated how anti-TcdB IgG anti...
34516580,Effective inhibition of Clostridioides diffici...,Clostridioides difficile infection is the most...,No,Yes,No,This study evaluated antimicrobial peptides as...
34496836,A budget impact analysis of bezlotoxumab versu...,Background: Clostridioides difficile infection...,No,No,No,This study conducted a budget impact analysis ...
34496003,The small acid-soluble proteins of Clostridioi...,Clostridioides difficile is a nosocomial patho...,Yes,No,No,This study explored the role of small acid-sol...
34659541,Safety and efficacy of fecal microbiota transp...,Background: Cancer patients are at increased r...,No,Yes,No,This study examined the safety and effectivene...
34492076,"Raja 42, a novel gamma lactam compound, is eff...",Clostridioides difficile infection (CDI) is th...,No,Yes,No,"This study explored the potential of Raja 42, ..."

In [69]:
esponse = clasificador.clasificacion(df.loc[34496836,"Abstract"])

KeyboardInterrupt:

In [64]:
def _transformacion_binario_val(col):
    if (col=="Yes") | (col==1):
        return 1
    elif (col=="No") | (col==0):
        return 0
def _transformacion_binario_df(df):
    df[['1) Antimicrobial Resistance stain',
        '2) New treatment','3) Immunization']] = df[['1) Antimicrobial Resistance stain',
                                                     '2) New treatment',
                                                     '3) Immunization']].applymap(_transformacion_binario_val)
    return df



def ask_llm(df_,partition=0):
    df=df_.copy()
    df=_transformacion_binario_df(df)
    if partition==0:
        for pmid in df.index:
            response = clasificador.clasificacion(df.loc[pmid,"Abstract"])
            df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
        return df
    else:
        print("aca")
        df_ptit=df.iloc[:10,:]
        print(df_ptit.index)
        for pmid in df_ptit.index:
            response = clasificador.clasificacion(df.loc[pmid,"Abstract"])
            df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
        return df_ptit

def _evaluate(row):
    values = row[["1) Antimicrobial Resistance stain","2) New treatment","3) Immunization"]].values
    ai_opcion=int(row["ai_label"])-1
    print(f"values={values}")
    print(f"ai_opcion{ai_opcion}")
    if (len(values)==0) & (ai_opcion==3):
        return 1
    elif (len(values)==0) & (ai_opcion<3):
        return 0
    elif (len(values)>0) & (ai_opcion==3):
        return 0
    elif values[ai_opcion]>0:

        return 1
    else:
        return 0

def evaluacion_score(df,partition=0):
    if partition ==0:
        n=df.shape[0]
        scores = df.apply(_evaluate,axis=1)
        final_score=sum(scores)/n
    else:
        df_ptit=df.iloc[:10,:]
        n=df_ptit.shape[0]
        scores=df_ptit.apply(_evaluate,axis=1)
        final_score=sum(scores)/n
    return final_score

In [65]:
df

,Title,Abstract,1) Antimicrobial Resistance stain,2) New treatment,3) Immunization,Human_summary
PMID,,,,,,
36466927,Neutralizing epitopes on Clostridioides diffic...,Toxin A (TcdA) and toxin B (TcdB) are two key ...,No,Yes,No,Using antibodies (VHHs) AH3 and AA6 are two po...
36439832,Peroxisome proliferator-activated receptor-γ a...,Clostridioides difficile is a major causative ...,No,Yes,No,"Administration of the PPAR-γ agonist, pioglita..."
36439215,The impact of dietary fibers on Clostridioides...,Diets rich in fiber may provide health benefit...,No,Yes,No,Use Inulin or pectin as a dietary-based therap...
36312948,Receptor binding protein of prophage reversibl...,Receptor-binding proteins (RBPs) are located a...,No,Yes,No,The paper studied a protein named PtsHN10M tha...
35042668,The emergence of Clostridioides difficile PCR ...,Background: Several studies have highlighted t...,Yes,No,No,This study focused on analyzing Clostridioides...
36093337,Antibiotic resistance and genomic features of ...,Background: Clostridioides difficile infection...,Yes,No,No,While current main treatments remain effective...
36026500,Characterization of the virulence of three nov...,Clostridioides (Clostridium) difficile infecti...,Yes,No,No,This study explored the emergence of novel Clo...
35939437,Discovery of a novel natural product inhibitor...,Clostridioides (Clostridium) difficile infecti...,Yes,No,No,This study was conducted in Brazil to better u...
33958010,Associations of facility-level antibiotic use ...,Previously reported associations between hospi...,Yes,No,No,This study reanalyzed the link between hospita...
35942219,Isobavachalcone From Cullen corylifolium Prese...,Background: Clostridium difficile infection (C...,No,Yes,No,This Study explored whether a traditional Chi...
35873420,Infant Formula With a Specific Blend of Five H...,Background: Human milk oligosaccharides (HMOs)...,No,No,Yes,Study whether infant formula supplemented with...
35844586,Corrigendum: Immunoinformatics approach toward...,"This corrects the article ""Immunoinformatics A...",No,No,No,"This corrects the article ""Immunoinformatics A..."
35217192,Clostridioides difficile from Brazilian hospit...,Clostridioides difficile (CD) is the most freq...,Yes,No,No,This study aimed to better understand non-toxi...
35125203,Clostridioides (Clostridium) difficile isolate...,Less is understood about the epidemiology of C...,Yes,No,No,This study provides a baseline for paediatric ...
34085620,Laboratory-identified vancomycin-resistant ent...,Background: We analyzed 2017 healthcare facili...,Yes,No,No,This study provides a baseline for paediatric ...
35677311,"Black Seed Oil, Bentonite Clay, and Probiotics...",There has been a rise in antibiotic resistance...,No,Yes,No,This case highlights the potential of compleme...
35720363,Immunoinformatics Approach Toward the Introduc...,Clostridium difficile (C.difficile) is an excl...,No,No,Yes,This in silico-designed vaccine could offer pr...
35078721,Rare toxin A-negative and toxin B-positive str...,Introduction: Clostridioides difficile (C. dif...,Yes,No,No,"This strain produces only toxin B, and such at..."
35469152,Novel structural insights for a pair of monocl...,Clostridium difficile toxins are the primary c...,No,Yes,No,The combination of B1 and B2 offers a promisin...
35104667,Linkage study of surveillance and hospital adm...,Objectives: Increasing incidence rates of Clos...,Yes,No,No,"CDI remains common in Western Australia, with ..."
35175750,"Design, Synthesis, and Characterization of TNP...","TNP-2198, a stable conjugate of a rifamycin ph...",No,Yes,No,This study introduces a novel antibacterial ag...
35360652,Molecular Epidemiology and Antimicrobial Resis...,Clostridioides difficile is a global public he...,Yes,No,No,This study reveals high genetic and toxin prof...
35252669,"Development of 1,2,4-Oxadiazole Antimicrobial ...",Colonization of the gastrointestinal (GI) trac...,No,Yes,No,"26a an analogue from 1,2,4-oxadiazole could se..."
34875405,Safety and Efficacy of Prophylactic Levofloxac...,Levofloxacin has been widely used for bacterem...,No,Yes,No,Levofloxacin prophylaxis during the peritrans...
35283831,Antigen-Specific vs. Neutralizing Antibodies A...,The immunological response against Clostridioi...,No,No,Yes,This study investigated the immune response in...
35107319,A Novel Bacteriophage with Broad Host Range ag...,Bacteriophages represent a promising option fo...,No,Yes,No,This study focuses on developing bacteriophage...
34612703,Evaluation of Piperacillin-Tazobactam for Anti...,Background: Broad-spectrum antibiotic agents a...,No,Yes,No,Piperacillin-tazobactam (PT) did not improve i...
35090351,Bezlotoxumab for Prevention of Recurrent Clost...,Objectives: Approximately 25% of patients with...,No,Yes,No,"Bezlotoxumab, a monoclonal antibody against C...."
35095921,Use of a Clostridioides difficile Murine Immun...,Adjuvant combinations may enhance or broaden t...,No,No,Yes,This study tested whether combining vaccine ad...
35016207,Emergence of Clinical Clostridioides difficile...,Background: Clostridioides difficile infection...,Yes,No,No,This study investigated if there are Vancomyci...
34991700,Myxopyronin B inhibits growth of a Fidaxomicin...,"The anaerobic, gastrointestinal pathogen Clost...",No,Yes,No,"This study evaluated the natural antibiotic, M..."
34107037,Genomic Analysis of Clostridioides difficile i...,Background: The distribution of Clostridioides...,Yes,No,No,This study examined the genetic diversity and ...
36045589,Bezlotoxumab prevents extraintestinal organ da...,Clostridioides difficile is the most common ca...,No,Yes,No,C. difficile toxins can cause systemic immune ...
35157277,Facile Affinity Maturation of Single-Domain An...,Binding affinity is one of the primary determi...,No,Yes,No,This study presents a fast and simple method t...
35036247,Microbiota diversity and bacterial load after ...,"In this letter, an experimental therapy in fou...",No,Yes,No,This scientific letter describes an experiment...
35008521,Specific Inhibition of VanZ-Mediated Resistanc...,Teicoplanin is a natural lipoglycopeptide anti...,Yes,Yes,No,This study investigated how certain bacteria—i...
34837818,"Studies on the Importance of the 7α-, and 12α-...",Chenodeoxycholic acid (CDCA) is a natural germ...,No,Yes,No,This study aimed to develop new inhibitors of ...
34955836,Soluble Non-Starch Polysaccharides From Planta...,Clostridioides difficile infection (CDI) is a ...,No,Yes,No,This study examined how soluble dietary fiber ...
34790963,Evaluation of Prolonged Versus Continuous Infu...,"Background: In 2017, a national drug shortage ...",No,Yes,No,This study evaluated continuous infusion of pi...
34775130,Real-world clinical outcomes of meropenem/vabo...,Objectives: Real-world data regarding the effe...,Yes,Yes,No,This case series reports real-world outcomes o...
33682630,New ribotype Clostridioides difficile from ST1...,Clostridioides difficile is the predominant an...,Yes,No,No,This study compared Clostridioides difficile R...
34835068,"Impact of Phage CDHS-1 on the Transcription, P...",All known Clostridioides difficile phages enco...,No,Yes,No,This study examined how the phage CDHS-1 infec...
34023223,Retrospective study of the efficacy and safety...,Introduction: According to the Japanese guidel...,No,Yes,No,This study evaluated whether Japanese guidelin...
36168487,Initial vancomycin versus metronidazole for th...,Objective: Clostridioides difficile infection ...,No,Yes,No,This study compared initial treatment with van...
34097471,The Murine Neonatal Fc Receptor Is Required fo...,The pathology associated with Clostridioides d...,No,No,No,This study investigated how anti-TcdB IgG anti...
34516580,Effective inhibition of Clostridioides diffici...,Clostridioides difficile infection is the most...,No,Yes,No,This study evaluated antimicrobial peptides as...
34496836,A budget impact analysis of bezlotoxumab versu...,Background: Clostridioides difficile infection...,No,No,No,This study conducted a budget impact analysis ...
34496003,The small acid-soluble proteins of Clostridioi...,Clostridioides difficile is a nosocomial patho...,Yes,No,No,This study explored the role of small acid-sol...
34659541,Safety and efficacy of fecal microbiota transp...,Background: Cancer patients are at increased r...,No,Yes,No,This study examined the safety and effectivene...
34492076,"Raja 42, a novel gamma lactam compound, is eff...",Clostridioides difficile infection (CDI) is th...,No,Yes,No,"This study explored the potential of Raja 42, ..."

In [66]:
df_new=ask_llm(df)

C:\Users\chris\AppData\Local\Temp\ipykernel_29648\3939741552.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

InferenceTimeoutError: Model not loaded on the server: https://api-inference.huggingface.co/models/mistralai/Mixtral-8x7B-Instruct-v0.1. Please retry with a higher timeout (current: 120).

In [59]:
df_new

,Title,Abstract,1) Antimicrobial Resistance stain,2) New treatment,3) Immunization,Human_summary,ai_label,ai_summary
PMID,,,,,,,,
36466927,Neutralizing epitopes on Clostridioides diffic...,Toxin A (TcdA) and toxin B (TcdB) are two key ...,0,1,0,Using antibodies (VHHs) AH3 and AA6 are two po...,3,"""The paper discusses the use of single-domain..."
36439832,Peroxisome proliferator-activated receptor-γ a...,Clostridioides difficile is a major causative ...,0,1,0,"Administration of the PPAR-γ agonist, pioglita...",NaN,NaN
36439215,The impact of dietary fibers on Clostridioides...,Diets rich in fiber may provide health benefit...,0,1,0,Use Inulin or pectin as a dietary-based therap...,NaN,NaN
36312948,Receptor binding protein of prophage reversibl...,Receptor-binding proteins (RBPs) are located a...,0,1,0,The paper studied a protein named PtsHN10M tha...,NaN,NaN
35042668,The emergence of Clostridioides difficile PCR ...,Background: Several studies have highlighted t...,1,0,0,This study focused on analyzing Clostridioides...,NaN,NaN
36093337,Antibiotic resistance and genomic features of ...,Background: Clostridioides difficile infection...,1,0,0,While current main treatments remain effective...,NaN,NaN
36026500,Characterization of the virulence of three nov...,Clostridioides (Clostridium) difficile infecti...,1,0,0,This study explored the emergence of novel Clo...,NaN,NaN
35939437,Discovery of a novel natural product inhibitor...,Clostridioides (Clostridium) difficile infecti...,1,0,0,This study was conducted in Brazil to better u...,NaN,NaN
33958010,Associations of facility-level antibiotic use ...,Previously reported associations between hospi...,1,0,0,This study reanalyzed the link between hospita...,NaN,NaN
35942219,Isobavachalcone From Cullen corylifolium Prese...,Background: Clostridium difficile infection (C...,0,1,0,This Study explored whether a traditional Chi...,NaN,NaN
35873420,Infant Formula With a Specific Blend of Five H...,Background: Human milk oligosaccharides (HMOs)...,0,0,1,Study whether infant formula supplemented with...,NaN,NaN
35844586,Corrigendum: Immunoinformatics approach toward...,"This corrects the article ""Immunoinformatics A...",0,0,0,"This corrects the article ""Immunoinformatics A...",NaN,NaN
35217192,Clostridioides difficile from Brazilian hospit...,Clostridioides difficile (CD) is the most freq...,1,0,0,This study aimed to better understand non-toxi...,NaN,NaN
35125203,Clostridioides (Clostridium) difficile isolate...,Less is understood about the epidemiology of C...,1,0,0,This study provides a baseline for paediatric ...,NaN,NaN
34085620,Laboratory-identified vancomycin-resistant ent...,Background: We analyzed 2017 healthcare facili...,1,0,0,This study provides a baseline for paediatric ...,NaN,NaN
35677311,"Black Seed Oil, Bentonite Clay, and Probiotics...",There has been a rise in antibiotic resistance...,0,1,0,This case highlights the potential of compleme...,NaN,NaN
35720363,Immunoinformatics Approach Toward the Introduc...,Clostridium difficile (C.difficile) is an excl...,0,0,1,This in silico-designed vaccine could offer pr...,NaN,NaN
35078721,Rare toxin A-negative and toxin B-positive str...,Introduction: Clostridioides difficile (C. dif...,1,0,0,"This strain produces only toxin B, and such at...",NaN,NaN
35469152,Novel structural insights for a pair of monocl...,Clostridium difficile toxins are the primary c...,0,1,0,The combination of B1 and B2 offers a promisin...,NaN,NaN
35104667,Linkage study of surveillance and hospital adm...,Objectives: Increasing incidence rates of Clos...,1,0,0,"CDI remains common in Western Australia, with ...",NaN,NaN
35175750,"Design, Synthesis, and Characterization of TNP...","TNP-2198, a stable conjugate of a rifamycin ph...",0,1,0,This study introduces a novel antibacterial ag...,NaN,NaN
35360652,Molecular Epidemiology and Antimicrobial Resis...,Clostridioides difficile is a global public he...,1,0,0,This study reveals high genetic and toxin prof...,NaN,NaN
35252669,"Development of 1,2,4-Oxadiazole Antimicrobial ...",Colonization of the gastrointestinal (GI) trac...,0,1,0,"26a an analogue from 1,2,4-oxadiazole could se...",NaN,NaN
34875405,Safety and Efficacy of Prophylactic Levofloxac...,Levofloxacin has been widely used for bacterem...,0,1,0,Levofloxacin prophylaxis during the peritrans...,NaN,NaN
35283831,Antigen-Specific vs. Neutralizing Antibodies A...,The immunological response against Clostridioi...,0,0,1,This study investigated the immune response in...,NaN,NaN
35107319,A Novel Bacteriophage with Broad Host Range ag...,Bacteriophages represent a promising option fo...,0,1,0,This study focuses on developing bacteriophage...,NaN,NaN
34612703,Evaluation of Piperacillin-Tazobactam for Anti...,Background: Broad-spectrum antibiotic agents a...,0,1,0,Piperacillin-tazobactam (PT) did not improve i...,NaN,NaN
35090351,Bezlotoxumab for Prevention of Recurrent Clost...,Objectives: Approximately 25% of patients with...,0,1,0,"Bezlotoxumab, a monoclonal antibody against C....",NaN,NaN
35095921,Use of a Clostridioides difficile Murine Immun...,Adjuvant combinations may enhance or broaden t...,0,0,1,This study tested whether combining vaccine ad...,NaN,NaN
35016207,Emergence of Clinical Clostridioides difficile...,Background: Clostridioides difficile infection...,1,0,0,This study investigated if there are Vancomyci...,NaN,NaN
34991700,Myxopyronin B inhibits growth of a Fidaxomicin...,"The anaerobic, gastrointestinal pathogen Clost...",0,1,0,"This study evaluated the natural antibiotic, M...",NaN,NaN
34107037,Genomic Analysis of Clostridioides difficile i...,Background: The distribution of Clostridioides...,1,0,0,This study examined the genetic diversity and ...,NaN,NaN
36045589,Bezlotoxumab prevents extraintestinal organ da...,Clostridioides difficile is the most common ca...,0,1,0,C. difficile toxins can cause systemic immune ...,NaN,NaN
35157277,Facile Affinity Maturation of Single-Domain An...,Binding affinity is one of the primary determi...,0,1,0,This study presents a fast and simple method t...,NaN,NaN
35036247,Microbiota diversity and bacterial load after ...,"In this letter, an experimental therapy in fou...",0,1,0,This scientific letter describes an experiment...,NaN,NaN
35008521,Specific Inhibition of VanZ-Mediated Resistanc...,Teicoplanin is a natural lipoglycopeptide anti...,1,1,0,This study investigated how certain bacteria—i...,NaN,NaN
34837818,"Studies on the Importance of the 7α-, and 12α-...",Chenodeoxycholic acid (CDCA) is a natural germ...,0,1,0,This study aimed to develop new inhibitors of ...,NaN,NaN
34955836,Soluble Non-Starch Polysaccharides From Planta...,Clostridioides difficile infection (CDI) is a ...,0,1,0,This study examined how soluble dietary fiber ...,NaN,NaN
34790963,Evaluation of Prolonged Versus Continuous Infu...,"Background: In 2017, a national drug shortage ...",0,1,0,This study evaluated continuous infusion of pi...,NaN,NaN
34775130,Real-world clinical outcomes of meropenem/vabo...,Objectives: Real-world data regarding the effe...,1,1,0,This case series reports real-world outcomes o...,NaN,NaN
33682630,New ribotype Clostridioides difficile from ST1...,Clostridioides difficile is the predominant an...,1,0,0,This study compared Clostridioides difficile R...,NaN,NaN
34835068,"Impact of Phage CDHS-1 on the Transcription, P...",All known Clostridioides difficile phages enco...,0,1,0,This study examined how the phage CDHS-1 infec...,NaN,NaN
34023223,Retrospective study of the efficacy and safety...,Introduction: According to the Japanese guidel...,0,1,0,This study evaluated whether Japanese guidelin...,NaN,NaN
36168487,Initial vancomycin versus metronidazole for th...,Objective: Clostridioides difficile infection ...,0,1,0,This study compared initial treatment with van...,NaN,NaN
34097471,The Murine Neonatal Fc Receptor Is Required fo...,The pathology associated with Clostridioides d...,0,0,0,This study investigated how anti-TcdB IgG anti...,NaN,NaN
34516580,Effective inhibition of Clostridioides diffici...,Clostridioides difficile infection is the most...,0,1,0,This study evaluated antimicrobial peptides as...,NaN,NaN
34496836,A budget impact analysis of bezlotoxumab versu...,Background: Clostridioides difficile infection...,0,0,0,This study conducted a budget impact analysis ...,NaN,NaN
34496003,The small acid-soluble proteins of Clostridioi...,Clostridioides difficile is a nosocomial patho...,1,0,0,This study explored the role of small acid-sol...,NaN,NaN
34659541,Safety and efficacy of fecal microbiota transp...,Background: Cancer patients are at increased r...,0,1,0,This study examined the safety and effectivene...,NaN,NaN
34492076,"Raja 42, a novel gamma lactam compound, is eff...",Clostridioides difficile infection (CDI) is th...,0,1,0,"This study explored the potential of Raja 42, ...",NaN,NaN