## Paper Auto-Classifier 📚
### 1) Importar Librerias

In [29]:
#Asegurate de tener activado el entorno de programación con el interprete python 3.11
# (En terminal) 
# pip install langchain_huggingface
# pip install tqdm

import pandas as pd 
import numpy as np
from LLM import Clasificador
from tqdm import tqdm

Unificar .CSV

In [ ]:
# import os
# import pandas as pd

# # Carpeta donde están los archivos
# carpeta = r"E:\LLMzCor\LLMzCor.github.io\WebScraping\Abstracts"

# # Lista de nombres de archivos que quieres concatenar
# nombres_archivos = [
#     "PMID_Hp.csv",
#     "PMID_Sh.csv",
#     "PMID_Kp.csv",
   
#     # agrega aquí los nombres que desees
# ]

# # Construye las rutas completas
# rutas = [os.path.join(carpeta, nombre) for nombre in nombres_archivos]

# # Lee y concatena los archivos
# df_list = [pd.read_csv(ruta) for ruta in rutas]
# df_concat = pd.concat(df_list, ignore_index=True)

# # Guarda el resultado si lo deseas
# Output_file_name = "compilado_Hp-Sh-Kp.csv"  # Cambia aquí el nombre como desees
# df_concat.to_csv(os.path.join(carpeta, Output_file_name ), index=False, encoding="utf-8-sig")

# print(f"Archivo guardado como: {Output_file_name}", rutas)
# print("Shape final:", df_concat.shape)

Archivo guardado como: compilado_Hp-Sh-Kp.csv ['E:\\LLMzCor\\LLMzCor.github.io\\WebScraping\\Abstracts\\PMID_Hp.csv', 'E:\\LLMzCor\\LLMzCor.github.io\\WebScraping\\Abstracts\\PMID_Sh.csv', 'E:\\LLMzCor\\LLMzCor.github.io\\WebScraping\\Abstracts\\PMID_Kp.csv']
Shape final: (37460, 2)

### 2) Carga BD de Bacterias 🦠🧫👨‍🔬👩‍🔬

In [30]:
#Modifica la ruta de la base de datos
#Selecona la pesataña del excel
file_path = r"E:\LLMzCor\LLMzCor.github.io\WebScraping\Abstracts\PMID_Ng.csv"
# sheet = "Test"
# usecols= [
#     'PMID',
#     'Title',
#     'Abstract',
#     #'Estado',
#     '1) Antimicrobial Resistance stain',
#     '2) New treatment',
#     '3) Immunization',
#     'Human_summary',
#     # 'Publication Year',
#     # 'Journal/Book',
#     # 'Alerta'
# ]
df = pd.read_csv(
    file_path,
    # sheet_name=sheet,
    # usecols=usecols, 
    index_col=0
)
df.shape

(3740, 1)

In [31]:
for col in [
    'Title',
    '1) Antimicrobial Resistance stain',
    '2) New treatment',
    '3) Immunization',
    'Human_summary',
]:
    if col not in df.columns: 
        df[col] = np.nan

#### Aplica filtros de Excluir (Opcional)

In [32]:
#Filtro los excluidos
# df = df[df['Estado']!="Excluir"]

# df_shape = df.shape

# #Calculo cuantos paper se excluyeron
# resta = df .shape[0]- df.shape[0]
# print("df Shape ", df_shape, " depués del filtro ", resta)

df.head()

,Title,1) Antimicrobial Resistance stain,2) New treatment,3) Immunization,Human_summary
PMID,,,,,
29430011,The host-adapted human pathogen Neisseria gono...,NaN,NaN,NaN,NaN
28991324,No abstract available,NaN,NaN,NaN,NaN
31119616,Gonorrhea and antimicrobial resistance (AMR) i...,NaN,NaN,NaN,NaN
31802195,Neisseria gonorrhoeae is an etiologic agent of...,NaN,NaN,NaN,NaN
28754299,Neisseria gonorrhoeae is the agent of gonorrhe...,NaN,NaN,NaN,NaN

#### _____________2.b) Carga de BD de Tratamientos ⚗️🧪👨‍🔬(Opcional)

In [7]:
#Caraga la base de datos de los tratamientos (tx) para cada bacteria
# treatment_path = r"E:\PaperLLM\LLMzCor.github.io\DBs\Treatment_2017.xlsx"
# tx_df = pd.read_excel(io= treatment_path, index_col=0)
# #tx_df.head()

# #Selecciona los tratamiento de primera eleccion utilizados hasta 2017
# Bacteria = "Chlamydia_trachomatis" 
# treatment= tx_df.loc[Bacteria,"First-line treatment until 2017"]
# print(treatment)

### 3) LLM Funciones ⚠️ Importante Ejecutar‼️

In [33]:
clasificador=Clasificador()

In [34]:
def _transformacion_binario_val(col):
    if (col=="Yes") | (col==1):
        return 1
    elif (col=="No") | (col==0):
        return 0
def _transformacion_binario_df(df):
    df[['1) Antimicrobial Resistance stain',
        '2) New treatment','3) Immunization']] = df[['1) Antimicrobial Resistance stain',
                                                     '2) New treatment',
                                                     '3) Immunization']].applymap(_transformacion_binario_val)
    return df



def ask_llm(df_,partition=0):
    df=df_.copy()
    df=_transformacion_binario_df(df)
    df["ai_label"]=np.nan
    df["ai_summary"]=np.nan
    if partition==0:
        for pmid in df.index:
            try:
                response = clasificador.clasificacion(df.loc[pmid,"Abstract"])
                df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
            except Exception as e:
                print(f"Se corto el proceso del LLM por este motivo : {e} en el id {pmid}")
                return df.loc[:pmid].iloc[:-1]
        return df
    else:
        print("aca")
        df_ptit=df.iloc[:partition,:]
        for pmid in df_ptit.index:
            try:
                response = clasificador.clasificacion(df_ptit.loc[pmid,"Abstract"])
                df_ptit.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
            except Exception as e:
                print(f"Se corto el proceso del LLM por este motivo : {e} en el id {pmid}")
                return df_ptit.loc[:pmid].iloc[:-1]
        return df_ptit

def _evaluate(row):
    values = row[["1) Antimicrobial Resistance stain","2) New treatment","3) Immunization"]].values
    ai_opcion=int(row["ai_label"])-1
    print(f"values={values}")
    print(f"ai_opcion{ai_opcion}")
    if (values.sum()==0) & (ai_opcion==3):
        return 1
    elif (values.sum()==0) & (ai_opcion<3):
        return 0
    elif (values.sum()>0) & (ai_opcion==3):
        return 0
    elif values[ai_opcion]>0:

        return 1
    else:
        return 0

def evaluacion_score(df,partition=0):
    if partition ==0:
        n=df.shape[0]
        scores = df.apply(_evaluate,axis=1)
        final_score=sum(scores)/n
    else:
        df_ptit=df.iloc[:10,:]
        n=df_ptit.shape[0]
        scores=df_ptit.apply(_evaluate,axis=1)
        final_score=sum(scores)/n
    return final_score

### _______________________Prueba clasificando un solo paper (Opcional)

In [18]:

paper=df.loc[22203235, "Abstract"]
#paper=df.loc[22525317, "Title"]
clasificador.clasificacion(paper)

['4',
 ' "The paper does not discuss Multiresistance bacteria stains report, neither new treatments nor immunization. Instead, it focuses on the mechanisms of Chlamydia pneumoniae invasion into nonphagocytic epithelial cells, specifically the role of cholesterol, sphingomyelin, and certain receptors in this process."']

### 4) Ask LLM to classify df

---
Abreviatura dataframes de bacterias:
+ df --> Chlamydia trachomatis
+ df_Cd --> Clostridium difficile
+ df_Hi --> Haemopilus influenzae
+ df_Kp --> Klebsiella pneumoniae
+ df_Ng --> Neisseria gonorrhoeae
+ df_Sh --> Shigela spp
+ df_Rk --> Ricketttsia
---

### 4b) Ask df_ptits Particionado

### ----------Automatización de clasificaciones ----------

In [36]:
import os
from datetime import datetime

# Define el tamaño de cada partición
batch_size = 10
df_list = []
file_base = os.path.splitext(os.path.basename(file_path))[0]

try:
    # Itera sobre el DataFrame en bloques de batch_size
    for start in range(0, df.shape[0], batch_size):
        end = start + batch_size
        df_ptit = df.iloc[start:end, :]
        print(f"Procesando filas {start} a {end-1}")
        df_classified = ask_llm(df_ptit)
        df_list.append(df_classified)

    # Une todos los resultados en un solo DataFrame
    df_Cta = pd.concat(df_list, ignore_index=False)
    print("Shape final:", df_Cta.shape)
    df_Cta.head()
except Exception as e:
    if df_list :
        df_partial = pd.concat(df_list, ignore_index=False)
        now = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        partial_path = f"{file_base}_partial_{now}.csv"
        df_partial.to_csv(partial_path, encoding='utf-8-sig')
        print(f"Guardado parcial en: {partial_path}")
        pmid = df_partial.index[-1]
    print(f"Se corto el proceso del LLM por este motivo : {e} en el id {pmid}")
    df_Cta = df_classified.loc[:pmid].iloc[:-1]
    print("Shape final:", df_Cta.shape)
    raise

Procesando filas 0 a 9
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29430011
Procesando filas 10 a 19
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28645177
Procesando filas 20 a 29
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34094619
Procesando filas 30 a 39
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32530860
Procesando filas 40 a 49
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29883770
Procesando filas 50 a 59
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25480491
Procesando filas 60 a 69
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33590810
Procesando filas 70 a 79
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31340021
Procesando filas 80 a 89
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33367585
Procesando filas 90 a 99
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27185804
Procesando filas 100 a 109
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27481245
Procesando filas 110 a 119
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32966677
Procesando filas 120 a 129
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26122105
Procesando filas 130 a 139
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32202529
Procesando filas 140 a 149
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27499432
Procesando filas 150 a 159
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25735717
Procesando filas 160 a 169
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23475972
Procesando filas 170 a 179

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32441045
Procesando filas 180 a 189
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27758727
Procesando filas 190 a 199
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29373697
Procesando filas 200 a 209
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30321622
Procesando filas 210 a 219
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27736753
Procesando filas 220 a 229
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32318263
Procesando filas 230 a 239
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23680903
Procesando filas 240 a 249
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 22214779
Procesando filas 250 a 259
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30808445
Procesando filas 260 a 269
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31955892
Procesando filas 270 a 279
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25365962
Procesando filas 280 a 289
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27301565
Procesando filas 290 a 299
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 22908152
Procesando filas 300 a 309
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31002306
Procesando filas 310 a 319
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30996106
Procesando filas 320 a 329
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23625842
Procesando filas 330 a 339
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25987627
Procesando filas 340 a 349
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 22941436
Procesando filas 350 a 359
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23063097
Procesando filas 360 a 369
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25605303
Procesando filas 370 a 379
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29891604
Procesando filas 380 a 389
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28893785
Procesando filas 390 a 399
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29991383
Procesando filas 400 a 409
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 22547617
Procesando filas 410 a 419
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24243873
Procesando filas 420 a 429
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34116342
Procesando filas 430 a 439
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32738086
Procesando filas 440 a 449
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26323884
Procesando filas 450 a 459
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 22550918
Procesando filas 460 a 469
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30410109
Procesando filas 470 a 479
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31211673
Procesando filas 480 a 489
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26760182
Procesando filas 490 a 499
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28232214
Procesando filas 500 a 509
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31137965
Procesando filas 510 a 519
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32807804
Procesando filas 520 a 529

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32964934
Procesando filas 530 a 539
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 22807549
Procesando filas 540 a 549
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30275084
Procesando filas 550 a 559
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23186215
Procesando filas 560 a 569
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24435165
Procesando filas 570 a 579
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27080231
Procesando filas 580 a 589
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26244506
Procesando filas 590 a 599
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31119624
Procesando filas 600 a 609
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31860664
Procesando filas 610 a 619
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27494921
Procesando filas 620 a 629
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24197163
Procesando filas 630 a 639
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 22995365
Procesando filas 640 a 649
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31869330
Procesando filas 650 a 659
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31760050
Procesando filas 660 a 669
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25022301
Procesando filas 670 a 679
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26967304
Procesando filas 680 a 689
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24066990
Procesando filas 690 a 699
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23903665
Procesando filas 700 a 709
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23836923
Procesando filas 710 a 719
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31119617
Procesando filas 720 a 729
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32071056
Procesando filas 730 a 739
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27682063
Procesando filas 740 a 749
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24532681
Procesando filas 750 a 759
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27442026
Procesando filas 760 a 769
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27577587
Procesando filas 770 a 779
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29798752
Procesando filas 780 a 789
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24002068
Procesando filas 790 a 799
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23341609
Procesando filas 800 a 809
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31872856
Procesando filas 810 a 819
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26165431
Procesando filas 820 a 829
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26949934
Procesando filas 830 a 839
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31119614
Procesando filas 840 a 849
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30206175
Procesando filas 850 a 859
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25175873
Procesando filas 860 a 869
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23615200
Procesando filas 870 a 879
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28615273
Procesando filas 880 a 889
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24184420
Procesando filas 890 a 899
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28604481
Procesando filas 900 a 909
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31095319
Procesando filas 910 a 919
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32967905
Procesando filas 920 a 929
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 22286973
Procesando filas 930 a 939
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29482499
Procesando filas 940 a 949
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27414503
Procesando filas 950 a 959
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26268281
Procesando filas 960 a 969
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29324629
Procesando filas 970 a 979

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28686231
Procesando filas 980 a 989
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32845194
Procesando filas 990 a 999
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 22399131
Procesando filas 1000 a 1009
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27506605
Procesando filas 1010 a 1019
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24836415
Procesando filas 1020 a 1029
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28003355
Procesando filas 1030 a 1039
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 35213551
Procesando filas 1040 a 1049
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29465642
Procesando filas 1050 a 1059
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34214531
Procesando filas 1060 a 1069
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24801359
Procesando filas 1070 a 1079
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31822275
Procesando filas 1080 a 1089
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33351912
Procesando filas 1090 a 1099
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25122855
Procesando filas 1100 a 1109
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30068746
Procesando filas 1110 a 1119
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34542856
Procesando filas 1120 a 1129
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32363389
Procesando filas 1130 a 1139
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28427377
Procesando filas 1140 a 1149
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23407126
Procesando filas 1150 a 1159
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 35811666
Procesando filas 1160 a 1169
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24275266
Procesando filas 1170 a 1179
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29856349
Procesando filas 1180 a 1189
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33763825
Procesando filas 1190 a 1199
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29155673
Procesando filas 1200 a 1209
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24571971
Procesando filas 1210 a 1219
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34755593
Procesando filas 1220 a 1229
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29066619
Procesando filas 1230 a 1239
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28701270
Procesando filas 1240 a 1249
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30249196
Procesando filas 1250 a 1259
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31662418
Procesando filas 1260 a 1269
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 35102276
Procesando filas 1270 a 1279
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28957453
Procesando filas 1280 a 1289
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34731020
Procesando filas 1290 a 1299
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34029611
Procesando filas 1300 a 1309
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23036167
Procesando filas 1310 a 1319
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28073612
Procesando filas 1320 a 1329
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33242473
Procesando filas 1330 a 1339
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26423658
Procesando filas 1340 a 1349
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33162204
Procesando filas 1350 a 1359
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28858332
Procesando filas 1360 a 1369
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23856883
Procesando filas 1370 a 1379
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32024723
Procesando filas 1380 a 1389
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26941028
Procesando filas 1390 a 1399
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27984552
Procesando filas 1400 a 1409
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26119074
Procesando filas 1410 a 1419
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34581604
Procesando filas 1420 a 1429
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31213219
Procesando filas 1430 a 1439

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33117493
Procesando filas 1440 a 1449
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24188607
Procesando filas 1450 a 1459
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31241038
Procesando filas 1460 a 1469
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30541468
Procesando filas 1470 a 1479
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29499642
Procesando filas 1480 a 1489
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27091503
Procesando filas 1490 a 1499
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29976520
Procesando filas 1500 a 1509
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31203584
Procesando filas 1510 a 1519
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31536154
Procesando filas 1520 a 1529
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32976359
Procesando filas 1530 a 1539
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28348864
Procesando filas 1540 a 1549
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34932932
Procesando filas 1550 a 1559
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34225553
Procesando filas 1560 a 1569
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24797914
Procesando filas 1570 a 1579
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26418128
Procesando filas 1580 a 1589
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31424547
Procesando filas 1590 a 1599
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23592974
Procesando filas 1600 a 1609
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32089824
Procesando filas 1610 a 1619
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27745575
Procesando filas 1620 a 1629
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32359875
Procesando filas 1630 a 1639
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24306007
Procesando filas 1640 a 1649
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30587234
Procesando filas 1650 a 1659
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30943191
Procesando filas 1660 a 1669
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32664833
Procesando filas 1670 a 1679
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24614721
Procesando filas 1680 a 1689
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33082236
Procesando filas 1690 a 1699
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23826337
Procesando filas 1700 a 1709
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30878688
Procesando filas 1710 a 1719
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26622046
Procesando filas 1720 a 1729
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28652307
Procesando filas 1730 a 1739
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33102576
Procesando filas 1740 a 1749
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29912682
Procesando filas 1750 a 1759
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28746372
Procesando filas 1760 a 1769
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 35007131
Procesando filas 1770 a 1779
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29034772
Procesando filas 1780 a 1789
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33928799
Procesando filas 1790 a 1799
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33886170
Procesando filas 1800 a 1809
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32829411
Procesando filas 1810 a 1819
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34496731
Procesando filas 1820 a 1829

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25485648
Procesando filas 1830 a 1839
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32712655
Procesando filas 1840 a 1849
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 35231823
Procesando filas 1850 a 1859
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26299582
Procesando filas 1860 a 1869
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28876289
Procesando filas 1870 a 1879
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27639378
Procesando filas 1880 a 1889
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31488838
Procesando filas 1890 a 1899
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25569801
Procesando filas 1900 a 1909
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27485832
Procesando filas 1910 a 1919
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28004550
Procesando filas 1920 a 1929
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23407470
Procesando filas 1930 a 1939
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33845205
Procesando filas 1940 a 1949
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34570799
Procesando filas 1950 a 1959
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30114369
Procesando filas 1960 a 1969
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31881862
Procesando filas 1970 a 1979
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25581808
Procesando filas 1980 a 1989
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24918549
Procesando filas 1990 a 1999
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 22349975
Procesando filas 2000 a 2009
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32213195
Procesando filas 2010 a 2019
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29715319
Procesando filas 2020 a 2029
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30074254
Procesando filas 2030 a 2039
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25114322
Procesando filas 2040 a 2049
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30901398
Procesando filas 2050 a 2059
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34919828
Procesando filas 2060 a 2069
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26511740
Procesando filas 2070 a 2079
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26846151
Procesando filas 2080 a 2089
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26773149
Procesando filas 2090 a 2099
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28369227
Procesando filas 2100 a 2109
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31205048
Procesando filas 2110 a 2119
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27200523
Procesando filas 2120 a 2129
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29066630
Procesando filas 2130 a 2139
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32004254
Procesando filas 2140 a 2149
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25980791
Procesando filas 2150 a 2159
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24016806
Procesando filas 2160 a 2169
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27124470
Procesando filas 2170 a 2179
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34475363
Procesando filas 2180 a 2189

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23759175
Procesando filas 2190 a 2199
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29486628
Procesando filas 2200 a 2209
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30838398
Procesando filas 2210 a 2219
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24633530
Procesando filas 2220 a 2229
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28360379
Procesando filas 2230 a 2239
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32089090
Procesando filas 2240 a 2249
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32202687
Procesando filas 2250 a 2259
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34755815
Procesando filas 2260 a 2269
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34433793
Procesando filas 2270 a 2279
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26165433
Procesando filas 2280 a 2289
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27797865
Procesando filas 2290 a 2299
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25229376
Procesando filas 2300 a 2309
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28636866
Procesando filas 2310 a 2319
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27629896
Procesando filas 2320 a 2329
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23965767
Procesando filas 2330 a 2339
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34557895
Procesando filas 2340 a 2349
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29255100
Procesando filas 2350 a 2359
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27724878
Procesando filas 2360 a 2369
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25211249
Procesando filas 2370 a 2379
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34396407
Procesando filas 2380 a 2389
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26904785
Procesando filas 2390 a 2399
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34096386
Procesando filas 2400 a 2409
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 35235608
Procesando filas 2410 a 2419
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31513653
Procesando filas 2420 a 2429
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 35905043
Procesando filas 2430 a 2439
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23588125
Procesando filas 2440 a 2449
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29898936
Procesando filas 2450 a 2459
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24956111
Procesando filas 2460 a 2469
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23800942
Procesando filas 2470 a 2479
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34396398
Procesando filas 2480 a 2489
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 35617304
Procesando filas 2490 a 2499
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26519942
Procesando filas 2500 a 2509
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34565231
Procesando filas 2510 a 2519
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31688719
Procesando filas 2520 a 2529
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26887890
Procesando filas 2530 a 2539
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32209954
Procesando filas 2540 a 2549
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34174039
Procesando filas 2550 a 2559
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25482819
Procesando filas 2560 a 2569
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32770977
Procesando filas 2570 a 2579

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29434478
Procesando filas 2580 a 2589
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32582133
Procesando filas 2590 a 2599
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24971225
Procesando filas 2600 a 2609
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32395427
Procesando filas 2610 a 2619
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29872530
Procesando filas 2620 a 2629
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34434298
Procesando filas 2630 a 2639
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27570316
Procesando filas 2640 a 2649
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 35386292
Procesando filas 2650 a 2659
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33976101
Procesando filas 2660 a 2669
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32973901
Procesando filas 2670 a 2679
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 35222300
Procesando filas 2680 a 2689
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34279817
Procesando filas 2690 a 2699
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32806522
Procesando filas 2700 a 2709
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32381609
Procesando filas 2710 a 2719
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33633700
Procesando filas 2720 a 2729
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25322708
Procesando filas 2730 a 2739
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26528045
Procesando filas 2740 a 2749
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30126088
Procesando filas 2750 a 2759
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27547739
Procesando filas 2760 a 2769
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34070767
Procesando filas 2770 a 2779
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34557869
Procesando filas 2780 a 2789
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30474539
Procesando filas 2790 a 2799
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24088850
Procesando filas 2800 a 2809

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34223105
Procesando filas 2810 a 2819
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 22877601
Procesando filas 2820 a 2829
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29573486
Procesando filas 2830 a 2839
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32214342
Procesando filas 2840 a 2849
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34706064
Procesando filas 2850 a 2859
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 35154028
Procesando filas 2860 a 2869
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25768859
Procesando filas 2870 a 2879
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24275271
Procesando filas 2880 a 2889
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26442504
Procesando filas 2890 a 2899
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30023502
Procesando filas 2900 a 2909
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32536685
Procesando filas 2910 a 2919
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 27254649
Procesando filas 2920 a 2929
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29276602
Procesando filas 2930 a 2939
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26743574
Procesando filas 2940 a 2949
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34903146
Procesando filas 2950 a 2959
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26313289
Procesando filas 2960 a 2969
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31551478
Procesando filas 2970 a 2979
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30466791
Procesando filas 2980 a 2989
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28432206
Procesando filas 2990 a 2999
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 22351512
Procesando filas 3000 a 3009
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34913715
Procesando filas 3010 a 3019
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34488704
Procesando filas 3020 a 3029
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32184310
Procesando filas 3030 a 3039
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34055431
Procesando filas 3040 a 3049
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26145099
Procesando filas 3050 a 3059
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 22877592
Procesando filas 3060 a 3069
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23819400
Procesando filas 3070 a 3079
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31524362
Procesando filas 3080 a 3089
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29733249
Procesando filas 3090 a 3099
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24523487
Procesando filas 3100 a 3109
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31331980
Procesando filas 3110 a 3119
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23529298
Procesando filas 3120 a 3129
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29708009
Procesando filas 3130 a 3139
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26880101
Procesando filas 3140 a 3149
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32207537
Procesando filas 3150 a 3159
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31728988
Procesando filas 3160 a 3169
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26208181
Procesando filas 3170 a 3179
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34763670
Procesando filas 3180 a 3189
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28377334
Procesando filas 3190 a 3199
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29692813
Procesando filas 3200 a 3209
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24508691
Procesando filas 3210 a 3219
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33760867
Procesando filas 3220 a 3229
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34221771
Procesando filas 3230 a 3239
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23198910
Procesando filas 3240 a 3249
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25796031
Procesando filas 3250 a 3259
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25532465
Procesando filas 3260 a 3269
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26322229
Procesando filas 3270 a 3279
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32826099
Procesando filas 3280 a 3289
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23413032
Procesando filas 3290 a 3299
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23965997
Procesando filas 3300 a 3309
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26607860
Procesando filas 3310 a 3319
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 34730611
Procesando filas 3320 a 3329
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23102593
Procesando filas 3330 a 3339
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24908687
Procesando filas 3340 a 3349
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28683780
Procesando filas 3350 a 3359
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32807891
Procesando filas 3360 a 3369
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31801895
Procesando filas 3370 a 3379
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28260146
Procesando filas 3380 a 3389
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32908008
Procesando filas 3390 a 3399
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23197282
Procesando filas 3400 a 3409
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28913082
Procesando filas 3410 a 3419
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 29553074
Procesando filas 3420 a 3429
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24516558
Procesando filas 3430 a 3439
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28362869
Procesando filas 3440 a 3449

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23805209
Procesando filas 3450 a 3459
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32928965
Procesando filas 3460 a 3469
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24086683
Procesando filas 3470 a 3479
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26771402
Procesando filas 3480 a 3489
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 22421690
Procesando filas 3490 a 3499
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25533217
Procesando filas 3500 a 3509
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32562845
Procesando filas 3510 a 3519
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28178111
Procesando filas 3520 a 3529
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25465668
Procesando filas 3530 a 3539
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28430679
Procesando filas 3540 a 3549
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31935208
Procesando filas 3550 a 3559
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 25375642
Procesando filas 3560 a 3569
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30520971
Procesando filas 3570 a 3579
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30502515
Procesando filas 3580 a 3589
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32829308
Procesando filas 3590 a 3599
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 23187982
Procesando filas 3600 a 3609
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30733424
Procesando filas 3610 a 3619
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32976356
Procesando filas 3620 a 3629
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26819339
Procesando filas 3630 a 3639
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32074119
Procesando filas 3640 a 3649
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26586777
Procesando filas 3650 a 3659
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 24462432
Procesando filas 3660 a 3669
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28662181
Procesando filas 3670 a 3679
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 28923377
Procesando filas 3680 a 3689
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32647750
Procesando filas 3690 a 3699
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 32883750
Procesando filas 3700 a 3709
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 31056291
Procesando filas 3710 a 3719
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 30926519
Procesando filas 3720 a 3729
Se corto el proceso del LLM por este motivo : 'Abstract' en el id 33417838
Procesando filas 3730 a 3739

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_11068\3837796252.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : 'Abstract' en el id 26372927
Shape final: (0, 7)

In [20]:
df_Cta.shape
df_Cta.head()

,Abstract,Title,1) Antimicrobial Resistance stain,2) New treatment,3) Immunization,Human_summary,ai_label,ai_summary
PMID,,,,,,,,
22304240,The direct interrogation of fleeting intermedi...,NaN,None,None,None,NaN,4,The abstract does not contain any information...
21848430,Chlamydial infection of the lower genital trac...,NaN,None,None,None,NaN,4,The abstract does not contain any information...
22042092,No abstract available,NaN,None,None,None,NaN,4,The abstract does not contain any information...
22203235,A gram-negative obligate intracellular bacteri...,NaN,None,None,None,NaN,4,The abstract does not contain any information...
22222354,Ribonucleotide reductases (RNRs) are essential...,NaN,None,None,None,NaN,4,The abstract does not contain any information...

In [ ]:
df_Cta.shape

### 5) Evaluar

In [67]:
evaluacion_score(df_Cta)

values=[1 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion3
values=[1 1 0]
ai_opcion0
values=[0 1 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion3
values=[0 1 0]
ai_opcion3
values=[0 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[0 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion1
values=[0 0 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[0 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion0
values=[0 0 0]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion0
values=[0 1 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[0 1 1]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[0 0 1]
ai_opcion2
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1

0.8287671232876712

# 6) Limpieza de Df

In [24]:
columns_excluded = ['1) Antimicrobial Resistance stain', 
                    '2) New treatment', 
                    '3) Immunization',  
                    'Human_summary'
                    ]

In [25]:
df_clean= df_Cta.drop(columns= columns_excluded)

In [26]:
df_clean

,Abstract,Title,ai_label,ai_summary
PMID,,,,
22304240,The direct interrogation of fleeting intermedi...,NaN,4,The abstract does not contain any information...
21848430,Chlamydial infection of the lower genital trac...,NaN,4,The abstract does not contain any information...
22042092,No abstract available,NaN,4,The abstract does not contain any information...
22203235,A gram-negative obligate intracellular bacteri...,NaN,4,The abstract does not contain any information...
22222354,Ribonucleotide reductases (RNRs) are essential...,NaN,4,The abstract does not contain any information...
...,...,...,...,...
36704557,Artificial tick feeding systems (ATFS) can be ...,NaN,4,The abstract does not contain any information...
36714306,"The sweet potato whitefly, Bemisia tabaci (Gen...",NaN,4,The abstract does not contain any information...
36726570,Zooplankton provides bacteria with a complex m...,NaN,4,The abstract does not contain any information...
35192040,Arthropods are known to harbor several endosym...,NaN,4,The abstract does not contain any information...
36909844,"Many arthropods host bacterial symbionts, some...",NaN,4,The abstract does not contain any information...

# EDA

In [27]:
print("Se analizaron ", df_clean.shape[0], " papers.")

Se analizaron  24967  papers.

#### AI Label:

1) Antimicrobial Resistance stain
2) New treatment
3) Immunization
4) None

In [28]:
df_clean['ai_label'].value_counts()

ai_label
4    24967
Name: count, dtype: int64