In [2]:
import pandas as pd

In [3]:
df=pd.read_excel("BD_paper2 LLMzCor (categorias).xlsx")

In [4]:
df.head()

,PMID,Title,Abstract,Categorias_Humanos,subcategoria_Humanos,fecha de publicación,PubYear
0,31615000,Can Ciprofloxacin be Used for Precision Treatm...,NaN,revisar,NaN,2019 Oct 14,2022
1,31099330,Gentamicin as an alternative to ceftriaxone in...,NaN,revisar,NaN,2019 May,2018
2,25464974,Discovery and characterization of a novel clas...,A high-throughput phenotypic screen for novel...,4) otros,caracterización,2015 Jun,2014
3,22972828,Longitudinal analysis of the evolution and dis...,A longitudinal study combining multilocus seq...,2) Nuevos tratamientos,NaN,2012 Dec,2014
4,26848972,Targeting an Essential GTPase Obg for the Deve...,A promising new drug target for the developme...,2) Nuevos tratamientos,2c) Droga de diseño,2016 Feb 5,2014

In [5]:
df['Categorias_Humanos'].unique()

array(['revisar', '4) otros', '2) Nuevos tratamientos ',
       ' 1) Reporte de cepas resistentes', '3) Inmunizacióm', nan],
      dtype=object)

In [6]:
df[df["Categorias_Humanos"].isnull()]

,PMID,Title,Abstract,Categorias_Humanos,subcategoria_Humanos,fecha de publicación,PubYear
61,28520925,The ironclad truth: how in vivo transcriptomic...,Neisseria gonorrhoeae is one of the most prev...,NaN,NaN,2017 Jul 31,2018
333,33720324,The Next-Generation of Neisseria gonorrhoeae A...,NaN,NaN,NaN,2021 Mar 31,2021

In [7]:
df['Categorias_Humanos'] = df['Categorias_Humanos'].fillna('revisar')

In [8]:
df['Categorias_Humanos'].unique()

array(['revisar', '4) otros', '2) Nuevos tratamientos ',
       ' 1) Reporte de cepas resistentes', '3) Inmunizacióm'],
      dtype=object)

In [9]:
df_clean=df[df['Categorias_Humanos'] != 'revisar']

In [10]:
df_clean['Categorias_Humanos'].unique()

array(['4) otros', '2) Nuevos tratamientos ',
       ' 1) Reporte de cepas resistentes', '3) Inmunizacióm'],
      dtype=object)

In [11]:
df.head()

,PMID,Title,Abstract,Categorias_Humanos,subcategoria_Humanos,fecha de publicación,PubYear
0,31615000,Can Ciprofloxacin be Used for Precision Treatm...,NaN,revisar,NaN,2019 Oct 14,2022
1,31099330,Gentamicin as an alternative to ceftriaxone in...,NaN,revisar,NaN,2019 May,2018
2,25464974,Discovery and characterization of a novel clas...,A high-throughput phenotypic screen for novel...,4) otros,caracterización,2015 Jun,2014
3,22972828,Longitudinal analysis of the evolution and dis...,A longitudinal study combining multilocus seq...,2) Nuevos tratamientos,NaN,2012 Dec,2014
4,26848972,Targeting an Essential GTPase Obg for the Deve...,A promising new drug target for the developme...,2) Nuevos tratamientos,2c) Droga de diseño,2016 Feb 5,2014

In [12]:
from LLM import Clasificador

c:\Users\christian.lombardo\Documents\PAC\LLMzCor.github.io\env_PAC\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [13]:
clasificador=Clasificador()

In [19]:
df_clean['PMID'][15]

32301751

In [20]:
df_clean['Abstract'][15]

' Background Sexually transmitted infections continue to be a major health \nconcern in sub-Saharan Africa where antimicrobial drugs are becoming \nineffective due to increasing resistance. Many healthcare seekers in lower \nsocio-economic settings depend on invasive alien plants administered by \ntraditional health practitioners to treat sexually transmitted infections. \nMethods Roots of selected plants were analysed for phytoconstituents using \nstandard methods. Both the disc diffusion model and microdilution technique \nwere used to determine the inhibition zone and minimum inhibitory \nconcentration (MIC) of plant extracts against six clinical fungal strains \nand standard strain of Neisseria gonorrhoea. One-way ANOVA was used to find \nsignificant differences. Results Different phytoconstituents such as \nalkaloids, steroids, cardiac glycosides, terpenes, flavonoids, tannins and \nsaponins were qualitatively detected, depending on plant species. Acetone \nextracted the highest number of phytoconstituents in Senna didymobotrya, \nwhile methanol revealed most from Ricinus communis. Senna didymobotrya \nshowed significant inhibition against Candida glabrata, C. krusei, C. \nparapsilosis and C. tropicalis. Dichloromethane extract of Catharanthus \nroseus and methanol extract of S. didymobotrya demonstrated excellent MIC \nvalues of 0.03 and 0.08 mg/mL, respectively, against C. glabrata. \nCatharanthus roseus, Opuntia ficus-indica and Ricinus communis demonstrated \nmoderate to good antigonococcal activity, with all exhibiting more than 63% \ninhibition. Catharanthus roseus had the best antigonococcal activity with a \nmoderate MIC value of 0.63 mg/mL. Conclusion Some of the plant extracts \ndemonstrated potency towards clinically isolated fungal strains and against \nN. gonorrhoea, which validate the notion that some of the species need \nfurther pharmacological studies for isolation and characterisation of \nactive compounds. '

In [21]:
df_clean['Categorias_Humanos'][15]

'2) Nuevos tratamientos '

In [16]:
clasificador.clasificacion(df_clean['Abstract'][12])

' [2 , "The abstract discusses the testing of various antimicrobials, alone and in combination, against Neisseria gonorrhoeae, suggesting it falls under the category of new treatments."]\n\nThe provided abstract for Question 2 discusses the testing of various antimicrobials, alone and in combination, against Neisseria gonorrhoeae. The aim is to find agents that are active against N. gonorrhoeae, which suggests it falls under the category of new treatments (category 2). The research identifies the highest potency antimicrobials and tests certain combinations that did not show antagonism. This information can guide larger scale susceptibility studies for antimicrobial resistant N. gonorrhoeae.'

In [17]:
clasificador.clasificacion(df_clean['Title'][3])

'\n\nAnswer 2: [4, "This abstract discusses the evolution and dissemination of Neisseria gonorrhoeae strains, including the development of resistance to ciprofloxacin and azithromycin. While not a direct discussion of vaccination or new treatments, it falls under the miscellaneous category related to Neisseria gonorrhoeae and antimicrobial resistance."]'

In [22]:
clasificador.clasificacion(df_clean['Title'][15])

'\n[4 , "This paper does not specifically discuss antimicrobial resistance, new treatments, or vaccination. Instead, it explores the antimicrobial activity of selected plants against fungal species isolated from South African AIDS patients and their antigonococcal activity, which makes it a miscellaneous topic related to Neisseria gonorrhoeae and antimicrobial resistance."]'

In [1]:
print("aca agregué la branch_christian")

aca agregué la branch_christian