## Paper Auto-Classifier 📚
### 1) Importar Librerias

In [1]:
#Asegurate de tener activado el entorno de programación con el interprete python 3.11
# (En terminal) 
# pip install langchain_huggingface
# pip install tqdm

import pandas as pd 
import numpy as np
from LLM import Clasificador
from tqdm import tqdm

e:\LLMzCor\env_LLMzCor_311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### 2) Carga BD de Bacterias 🦠🧫👨‍🔬👩‍🔬

In [34]:
#Modifica la ruta de la base de datos
#Selecona la pesataña del excel
file_path = r"E:\LLMzCor\LLMzCor.github.io\Test\Test_files\test_file_B.xlsx"
# sheet = "Test"
usecols= [
    'PMID',
    'Title',
    'Abstract',
    #'Estado',
    '1) Antimicrobial Resistance stain',
    '2) New treatment',
    '3) Immunization',
    'Human_summary',
    # 'Publication Year',
    # 'Journal/Book',
    # 'Alerta'
]
df = pd.read_excel(
    io=file_path,
    # sheet_name=sheet,
    usecols=usecols, index_col=0
)

In [35]:
#df-unfilter.head()
df.shape

(1145, 6)

#### Aplica filtros de Excluir (Opcional)

In [36]:
#Filtro los excluidos
# df = df[df['Estado']!="Excluir"]

df_shape = df.shape

#Calculo cuantos paper se excluyeron
resta = df .shape[0]- df.shape[0]
print("df Shape ", df_shape, " depués del filtro ", resta)

df.head()

df Shape  (1145, 6)  depués del filtro  0

,Title,Abstract,1) Antimicrobial Resistance stain,2) New treatment,3) Immunization,Human_summary
PMID,,,,,,
34485172,Pharmacokinetics and Pharmacodynamics of a Nov...,Phage therapy is one of the most promising alt...,1,1,0,Phage øKp_Pokalde_002 is a potent therapeutic ...
34228538,Enhanced Antibacterial Activity of Repurposed ...,Klebsiella pneumoniae is an opportunistic Gram...,1,1,0,A lytic phage-mitomycin C combination was effe...
34199531,Dehydroabietic Acid Microencapsulation Potenti...,The antimicrobial activity of dehydroabietic a...,0,1,0,The obtained results indicate that DHA is a pr...
35663465,Airway Epithelial Cells Differentially Adapt T...,Background: Pneumonia is often elicited by bac...,0,0,0,Study of type-2-alveolar-epithelial-cells inmu...
30266769,Human Factor H Domains 6 and 7 Fused to IgG1 F...,Novel therapeutics against multidrug-resistant...,0,1,0,Human Factor H Domains 6 and 7 Fused to IgG1 F...

#### _____________2.b) Carga de BD de Tratamientos ⚗️🧪👨‍🔬(Opcional)

In [ ]:
#Caraga la base de datos de los tratamientos (tx) para cada bacteria
treatment_path = r"E:\PaperLLM\LLMzCor.github.io\DBs\Treatment_2017.xlsx"
tx_df = pd.read_excel(io= treatment_path, index_col=0)
#tx_df.head()

#Selecciona los tratamiento de primera eleccion utilizados hasta 2017
Bacteria = "Chlamydia_trachomatis" 
treatment= tx_df.loc[Bacteria,"First-line treatment until 2017"]
print(treatment)

### 3) LLM Funciones ⚠️ Importante Ejecutar‼️

In [37]:
clasificador=Clasificador()

In [38]:
def _transformacion_binario_val(col):
    if (col=="Yes") | (col==1):
        return 1
    elif (col=="No") | (col==0):
        return 0
def _transformacion_binario_df(df):
    df[['1) Antimicrobial Resistance stain',
        '2) New treatment','3) Immunization']] = df[['1) Antimicrobial Resistance stain',
                                                     '2) New treatment',
                                                     '3) Immunization']].applymap(_transformacion_binario_val)
    return df



def ask_llm(df_,partition=0):
    df=df_.copy()
    df=_transformacion_binario_df(df)
    df["ai_label"]=np.nan
    df["ai_summary"]=np.nan
    if partition==0:
        for pmid in df.index:
            try:
                response = clasificador.clasificacion(df.loc[pmid,"Title"])
                df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
            except Exception as e:
                print(f"Se corto el proceso del LLM por este motivo : {e} en el id {pmid}")
                return df.loc[:pmid].iloc[:-1]
        return df
    else:
        print("aca")
        df_ptit=df.iloc[:partition,:]
        for pmid in df_ptit.index:
            try:
                response = clasificador.clasificacion(df_ptit.loc[pmid,"Title"])
                df_ptit.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
            except Exception as e:
                print(f"Se corto el proceso del LLM por este motivo : {e} en el id {pmid}")
                return df_ptit.loc[:pmid].iloc[:-1]
        return df_ptit

def _evaluate(row):
    values = row[["1) Antimicrobial Resistance stain","2) New treatment","3) Immunization"]].values
    ai_opcion=int(row["ai_label"])-1
    print(f"values={values}")
    print(f"ai_opcion{ai_opcion}")
    if (values.sum()==0) & (ai_opcion==3):
        return 1
    elif (values.sum()==0) & (ai_opcion<3):
        return 0
    elif (values.sum()>0) & (ai_opcion==3):
        return 0
    elif values[ai_opcion]>0:

        return 1
    else:
        return 0

def evaluacion_score(df,partition=0):
    if partition ==0:
        n=df.shape[0]
        scores = df.apply(_evaluate,axis=1)
        final_score=sum(scores)/n
    else:
        df_ptit=df.iloc[:10,:]
        n=df_ptit.shape[0]
        scores=df_ptit.apply(_evaluate,axis=1)
        final_score=sum(scores)/n
    return final_score

### _______________________Prueba clasificando un solo paper (Opcional)

In [15]:

#paper=df.loc[22304240, "Abstract"]
#paper=df.loc[22525317, "Title"]
#clasificador.clasificacion(paper)

### 4) Ask LLM to classify df

---
Abreviatura dataframes de bacterias:
+ df --> Chlamydia trachomatis
+ df_Cd --> Clostridium difficile
+ df_Hi --> Haemopilus influenzae
+ df_Kp --> Klebsiella pneumoniae
+ df_Ng --> Neisseria gonorrhoeae
+ df_Sh --> Shigela spp
+ df_Rk --> Ricketttsia
---

###  4) Partición del df (Opcional) 🚧🚩Crhistian ver aquí 🚩🚧
Aunque df_ptit le pasa 10 o20  papers nos devuelve solo 9

### 4a) Ask_llm(df) Data Frame sin particionar

In [39]:
df_Ct = ask_llm(df)
shape_df= df_Ct.shape


print( " Shape df_classified ", shape_df )

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a novel virulent Klebsiella phage, which implies a potential new treatment for Klebsiella infections.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 30787927
 Shape df_classified  (10, 8)

### 4b) Ask df_ptits Particionado

In [48]:
df_ptit=df.iloc[:10,:]
shape_df_ptit= df_ptit.shape

df_classified_1 = ask_llm(df_ptit)
shape_df= df_classified_1.shape
print("--------------------------------------------------------")

print(" The df_ptit shape is ", shape_df_ptit, ", The df_classified shape is """, shape_df )
df_classified_1[0:10][["Title","ai_label","ai_summary"]]

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a novel virulent Klebsiella phage, which implies a potential new treatment for Klebsiella infections.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

--------------------------------------------------------
 The df_ptit shape is  (10, 6) , The df_classified shape is  (10, 8)

,Title,ai_label,ai_summary
PMID,,,
34485172,Pharmacokinetics and Pharmacodynamics of a Nov...,2,'The paper discusses a novel virulent Klebsie...
34228538,Enhanced Antibacterial Activity of Repurposed ...,2,'The paper discusses an enhanced antibacteria...
34199531,Dehydroabietic Acid Microencapsulation Potenti...,2,'The paper discusses the potential of Dehydro...
35663465,Airway Epithelial Cells Differentially Adapt T...,4,'The paper does not discuss multiresistance b...
30266769,Human Factor H Domains 6 and 7 Fused to IgG1 F...,2,'The paper discusses a new immunotherapeutic ...
35067598,Molecular Surveillance and Prediction of Antim...,1,'The paper discusses molecular surveillance a...
31654792,Is there a future for the ongoing use of azith...,2,'The paper discusses the future use of azithr...
31344102,Resistance of Neisseria gonorrhoeae isolates t...,1,'The abstract discusses the resistance of Nei...
29776806,Resistant gonorrhoea: east meets west,4,'The abstract does not discuss multiresistanc...
25990954,Inhibitory activities of the marine streptomyc...,2,'The paper discusses the inhibitory activitie...

In [41]:
df_ptit=df.iloc[10:20,:]
shape_df_ptit= df_ptit.shape

df_classified_2 = ask_llm(df_ptit)
shape_df= df_classified_2.shape


print("Shape df_ptit ", shape_df_ptit, ", Shape df_classified ", shape_df )

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : list index out of range en el id 30787927
Shape df_ptit  (10, 6) , Shape df_classified  (0, 8)

In [42]:
df_ptit=df.iloc[20:30,:]
shape_df_ptit= df_ptit.shape

df_classified_3 = ask_llm(df_ptit)
shape_df= df_classified_3.shape


print("Shape df_ptit ", shape_df_ptit, ", Shape df_classified ", shape_df )
df_classified_3

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a strain of Neisseria gonorrhoeae that has developed resistance to both ceftriaxone and high-level azithromycin, which are commonly used treatments for gonorrhoea, thus it falls under the category of multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 27389169
Shape df_ptit  (10, 6) , Shape df_classified  (1, 8)

,Title,Abstract,1) Antimicrobial Resistance stain,2) New treatment,3) Immunization,Human_summary,ai_label,ai_summary
PMID,,,,,,,,
29991383,Gonorrhoea treatment failure caused by a Neiss...,We describe a gonorrhoea case with combined hi...,1,0,0,"Creo que está mal catalogado, es más un caso d...",1,'The paper discusses a strain of Neisseria go...

In [49]:
df_ptit=df.iloc[30:40,:]
shape_df_ptit= df_ptit.shape

df_classified_4 = ask_llm(df_ptit)
shape_df= df_classified_4.shape


print("Shape df_ptit ", shape_df_ptit, ", Shape df_classified ", shape_df )

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a new treatment for infections caused by multidrug-resistant Klebsiella pneumoniae using topically applied bacteriophage in a rat model.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 26131720
Shape df_ptit  (10, 6) , Shape df_classified  (3, 8)

In [50]:
df_ptit=df.iloc[40:50,:]
shape_df_ptit= df_ptit.shape

df_classified_5 = ask_llm(df_ptit)
shape_df= df_classified_5.shape


print("Shape df_ptit ", shape_df_ptit, ", Shape df_classified ", shape_df )

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the modulatory effects of caffeine and pentoxifylline on aromatic antibiotics, suggesting a potential role in enhancing antibiotic efficacy, which falls under the category of New Treatments.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34516580
Shape df_ptit  (10, 6) , Shape df_classified  (2, 8)

In [51]:
df_ptit=df.iloc[50:60,:]
shape_df_ptit= df_ptit.shape

df_classified_6 = ask_llm(df_ptit)
shape_df= df_classified_6.shape


print("Shape df_ptit ", shape_df_ptit, ", Shape df_classified ", shape_df )

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the in-vitro activity of several new or comparative antimicrobial agents, including cefiderocol, cefepime/zidebactam, cefepime/enmetazobactam, omadacycline, and eravacycline, against carbapenem-nonsusceptible Enterobacterales. This focus on new treatments aligns with category 2.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Shape df_ptit  (10, 6) , Shape df_classified  (10, 8)

In [52]:
df_ptit=df.iloc[60:70,:]
shape_df_ptit= df_ptit.shape

df_classified_7 = ask_llm(df_ptit)
shape_df= df_classified_7.shape


print("Shape df_ptit ", shape_df_ptit, ", Shape df_classified ", shape_df )

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses ceftriaxone resistance in Neisseria gonorrhoeae, which falls under the category of multiresistance bacteria stains report. It does not discuss new treatments or immunization.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 28931240
Shape df_ptit  (10, 6) , Shape df_classified  (4, 8)

In [53]:
df_ptit=df.iloc[70:80,:]
shape_df_ptit= df_ptit.shape

df_classified_8 = ask_llm(df_ptit)
shape_df= df_classified_8.shape


print("Shape df_ptit ", shape_df_ptit, ", Shape df_classified ", shape_df )

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper does not discuss multiresistance bacteria stains report, new treatments, nor immunization. Instead, it focuses on the prevalence and dominance of specific variants of Chlamydia trachomatis L serovars in the U.S.A.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 26089520
Shape df_ptit  (10, 6) , Shape df_classified  (2, 8)

In [54]:
df_ptit=df.iloc[80:90,:]
shape_df_ptit= df_ptit.shape

df_classified_9 = ask_llm(df_ptit)
shape_df= df_classified_9.shape


print("Shape df_ptit ", shape_df_ptit, ", Shape df_classified ", shape_df )

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a potential new treatment for Neisseria gonorrhoeae infections, focusing on the use of the C4BP-IgM protein as a therapeutic approach.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Shape df_ptit  (10, 6) , Shape df_classified  (10, 8)

In [55]:
df_ptit=df.iloc[90:100,:]
shape_df_ptit= df_ptit.shape

df_classified_10 = ask_llm(df_ptit)
shape_df= df_classified_10.shape


print("Shape df_ptit ", shape_df_ptit, ", Shape df_classified ", shape_df )

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses the characterization of azithromycin-resistant Neisseria gonorrhoeae, which falls under the category of multidrug-resistant bacteria stains.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 24378136
Shape df_ptit  (10, 6) , Shape df_classified  (4, 8)

In [64]:
df_lista= [df_classified_1, 
             df_classified_2, 
             df_classified_3, 
             df_classified_4, 
             df_classified_5, 
             df_classified_6, 
             df_classified_8, 
             df_classified_7, 
             df_classified_9, 
             df_classified_10
            ]
df_Cta = pd.concat(df_lista, ignore_index=False)

In [65]:
print(df_Cta.shape)

df_Cta

(46, 8)

,Title,Abstract,1) Antimicrobial Resistance stain,2) New treatment,3) Immunization,Human_summary,ai_label,ai_summary
PMID,,,,,,,,
34485172,Pharmacokinetics and Pharmacodynamics of a Nov...,Phage therapy is one of the most promising alt...,1,1,0,Phage øKp_Pokalde_002 is a potent therapeutic ...,2,'The paper discusses a novel virulent Klebsie...
34228538,Enhanced Antibacterial Activity of Repurposed ...,Klebsiella pneumoniae is an opportunistic Gram...,1,1,0,A lytic phage-mitomycin C combination was effe...,2,'The paper discusses an enhanced antibacteria...
34199531,Dehydroabietic Acid Microencapsulation Potenti...,The antimicrobial activity of dehydroabietic a...,0,1,0,The obtained results indicate that DHA is a pr...,2,'The paper discusses the potential of Dehydro...
35663465,Airway Epithelial Cells Differentially Adapt T...,Background: Pneumonia is often elicited by bac...,0,0,0,Study of type-2-alveolar-epithelial-cells inmu...,4,'The paper does not discuss multiresistance b...
30266769,Human Factor H Domains 6 and 7 Fused to IgG1 F...,Novel therapeutics against multidrug-resistant...,0,1,0,Human Factor H Domains 6 and 7 Fused to IgG1 F...,2,'The paper discusses a new immunotherapeutic ...
35067598,Molecular Surveillance and Prediction of Antim...,Background: The aims of this study was to desc...,1,0,0,"Multidrug-resistant strains Northern Alberta, ...",1,'The paper discusses molecular surveillance a...
31654792,Is there a future for the ongoing use of azith...,Is there a future for the ongoing use of azith...,0,1,0,NaN,2,'The paper discusses the future use of azithr...
31344102,Resistance of Neisseria gonorrhoeae isolates t...,The goal of this work was to study the phenoty...,1,0,0,Resistance to different drugs and the genetic ...,1,'The abstract discusses the resistance of Nei...
29776806,Resistant gonorrhoea: east meets west,Resistant gonorrhoea: east meets west,1,0,0,NaN,4,'The abstract does not discuss multiresistanc...
25990954,Inhibitory activities of the marine streptomyc...,Infectious diseases caused by chlamydia or sch...,0,1,0,Sponge-associated actinomycetes represent a ri...,2,'The paper discusses the inhibitory activitie...
29991383,Gonorrhoea treatment failure caused by a Neiss...,We describe a gonorrhoea case with combined hi...,1,0,0,"Creo que está mal catalogado, es más un caso d...",1,'The paper discusses a strain of Neisseria go...
34572629,Topically Applied Bacteriophage to Control Mul...,(Background): Multi-drug-resistant Klebsiella ...,1,0,0,Phagos showed the highest healing efficiency b...,2,'The paper discusses a new treatment for infe...
35078664,Seroprevalence of IgG and IgM antibodies to Ha...,"Background: Over the last 2 decades, Haemophil...",0,0,1,Study on anti-Hia antibodies in children of va...,3,"""The paper discusses the seroprevalence of Ig..."
35865823,Isolation and Characterization of vB_kpnM_17-1...,Phages and phage-encoded proteins exhibit prom...,0,1,0,A phage showed excellent in vitro and in vivo ...,2,'The paper discusses the isolation and charac...
34198510,Modulatory Effects of Caffeine and Pentoxifyll...,Antimicrobial resistance is a major healthcare...,1,1,0,It was observed a modulatory effect of xanthin...,2,'The paper discusses the modulatory effects o...
32479537,Antimicrobial susceptibility profile of Gonoco...,Background: Neisseria gonorrhoeae (gonococcus)...,1,0,0,high level of fluoroquinolone resistance,1,"""The paper focuses on the antimicrobial susce..."
34166777,"In-vitro activity of cefiderocol, cefepime/zid...",This study examined the susceptibility of carb...,1,1,0,New antibiotics combinations were active again...,2,'The paper discusses the in-vitro activity of...
32849365,Exploration of Antibiotic Activity of Aminogly...,The emergence of infections caused by bacteria...,0,1,0,Ribostamycin shows potent in vitro activity ag...,2,'The paper discusses the exploration of antib...
25253760,"Ceftriaxone-resistant Neisseria gonorrhoeae, P...",Emergence and spread of multidrug-resistant Ne...,1,0,0,Not available,1,'The abstract discusses Ceftriaxone-resistant...
35095921,Use of a Clostridioides difficile Murine Immun...,Adjuvant combinations may enhance or broaden t...,0,0,1,This study tested whether combining vaccine ad...,3,'The paper directly stimulates the immune sys...
34208698,Evaluation of Benzguinols as Next-Generation A...,"Our recent focus on the ""lost antibiotic"" ungu...",1,1,0,Benzguinols were effective against resistant-K...,2,'The paper discusses the evaluation of Benzgu...
22427578,Genome-wide identification of Chlamydia tracho...,Purpose: Chlamydia trachomatis is the leading ...,0,0,1,"The current study, by mapping immunodominant C...",4,"""The paper's abstract discusses the genome-wi..."
36945223,Effect of rifampicin combination-regimens agai...,It is well-acknowledged that 'combination ther...,1,1,0,Rifampicin-cefotaxime and rifampicin-tetracycl...,1,'The paper discusses the effect of certain tr...
32059844,Crystal structure of Haemophilus influenzae 3-...,3-isopropylmalate dehydrogenases (LeuB) belong...,0,1,0,"LeuB from H. influenzae, essential for leucine...",4,"""The paper discusses the crystal structure of..."
30676251,Evaluation of Susceptibilities to Carbapenems ...,Neisseria gonorrhoeae is a principal pathogen ...,1,0,0,susceptibility to a series of carbapenems,1,'The paper evaluates the susceptibilities of ...
27148489,Defining the Binding Region in Factor H to Dev...,Non-typeable Haemophilus influenzae (NTHi) cau...,0,1,0,An FH6.7/Fc immunotherapeutic was designed tha...,2,'The paper discusses the development of a the...
24828565,Chlamydia trachomatis L serovars and dominance...,"Chlamydia trachomatis serovars L1, L2, L3 caus...",0,0,0,They detect new serovars but sensitive to anti...,4,'The paper does not discuss multiresistance b...
35845772,A Class IIb Bacteriocin Plantaricin NC8 Modula...,The gut microbiota is engaged in multiple inte...,0,1,0,PLNC8 modulates gut microbiota composition acr...,2,"'The paper discusses a Class IIb Bacteriocin,..."
26472770,First nationwide study regarding ceftriaxone r...,Objectives: Antimicrobial resistance (AMR) in ...,1,0,0,"ceftriaxone genetic resistance determinants, ...",1,'The paper discusses ceftriaxone resistance i...
31203584,"Australian Gonococcal Surveillance Programme, ...","Australian Gonococcal Surveillance Programme, ...",1,0,0,NaN,1,'The abstract discusses the Australian Gonoco...
25668641,Association of the in vitro susceptibility of ...,Background: The presence of persistent Chlamyd...,0,1,0,They assayed 7 antibiotics against 61 clinical...,4,'The paper does not discuss multiresistance b...
36312948,Receptor binding protein of prophage reversibl...,Receptor-binding proteins (RBPs) are located a...,0,1,0,The paper studied a protein named PtsHN10M tha...,4,"""The paper discusses the receptor binding pro..."
31661468,C4BP-IgM protein as a therapeutic approach to ...,Gonorrhea is a sexually transmitted infection ...,0,1,0,C4BP-IgM as a therapeutic strategy,2,'The paper discusses a potential new treatmen...
27986898,Antimicrobial activity of antisense peptide-pe...,Background: Antisense peptide nucleic acids (P...,0,1,0,An optimized PNA-peptide against acpP shows lo...,2,'The paper discusses a new potential treatmen...
32983076,In vitro Photodynamic Therapy of Polymicrobial...,Otitis media (OM) is a prevalent pediatric inf...,0,1,0,Antibacterial photodynamic therapy with Ce6 an...,2,"'The paper discusses Photodynamic Therapy, a ..."
25182063,In vitro activities of the novel bicyclolides ...,Objectives: New antimicrobials are essential t...,0,1,0,"novel bicyclolides modithromycin (EDP-420, EP-...",2,'The paper discusses the in vitro activities ...
34506927,Novel strains of Klebsiella africana and Klebs...,Over the past decade human associated multidru...,1,0,0,It indicates that a bat species are not reserv...,1,'The abstract discusses the discovery of nove...
24049157,Characteristics of males infected with common ...,We analyzed 265 urethral Neisseria gonorrhoeae...,1,0,0,epidemiology of gonorrhea in the United States,4,"""The abstract does not discuss multiresistanc..."
34775130,Real-world clinical outcomes of meropenem/vabo...,Objectives: Real-world data regarding the effe...,1,1,0,This case series reports real-world outcomes o...,2,'The paper discusses the clinical outcomes of...
28822976,Persistence after treatment of pharyngeal gono...,Introduction: Infection of Neisseria gonorrhoe...,1,0,0,Strains resistant despite treatment or very ea...,4,'The abstract does not discuss multiresistanc...
28303829,Mutation pattern in the genome of Neisseria go...,"Mutations in PenA, PorB, MtrE and MtrR genes r...",1,0,0,"Key mutations in N. gonorrhoeae genes porB, mt...",1,'The paper discusses the mutation pattern in ...
35967879,In vitro selection of Neisseria gonorrhoeae un...,The emergence of Neisseria gonorrhoeae strains...,1,0,0,Multidrug-resistant strains,1,'The paper discusses the selection of Neisser...
24571786,Characterization of azithromycin-resistant Nei...,A total of 122 Neisseria gonorrhoeae isolated ...,1,0,0,To assess azithromycin and ceftriaxone suscept...,1,'The abstract discusses the characterization ...
34772585,"Screening of anti-microbial, anti-biofilm acti...",Background: Shigellosis is an infectious intes...,0,1,0,The designed formulation was effective and non...,2,'The paper discusses the development of a new...
22293657,First reported case of the Swedish new variant...,Chlamydia trachomatis infections are the most ...,1,0,0,New strain found in Russia,4,'The paper does not discuss multiresistance b...
35386469,Decreased Susceptibility of Shigella Isolates ...,Azithromycin (AZT) has widely been used for th...,1,0,0,High prevalence of mph(A) gene in Shigella spp...,1,'The abstract discusses decreased susceptibil...

### ----------Prueba de automatización de clasificaciones ----------

In [66]:
# Define el tamaño de cada partición
batch_size = 10
df_list = []

# Itera sobre el DataFrame en bloques de batch_size
for start in range(0, df.shape[0], batch_size):
    end = start + batch_size
    df_ptit = df.iloc[start:end, :]
    print(f"Procesando filas {start} a {end-1}")
    df_classified = ask_llm(df_ptit)
    df_list.append(df_classified)

# Une todos los resultados en un solo DataFrame
df_Cta = pd.concat(df_list, ignore_index=False)
print("Shape final:", df_Cta.shape)
df_Cta.head()

Procesando filas 0 a 9

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a novel virulent Klebsiella phage, which implies a potential new treatment for Klebsiella infections.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 10 a 19

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : list index out of range en el id 30787927
Procesando filas 20 a 29

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a strain of Neisseria gonorrhoeae that has developed resistance to both ceftriaxone and high-level azithromycin, which are commonly used treatments for gonorrhoea, thus it falls under the category of multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 27389169
Procesando filas 30 a 39

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a new treatment for infections caused by multidrug-resistant Klebsiella pneumoniae using topically applied bacteriophage in a rat model.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 26131720
Procesando filas 40 a 49

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the modulatory effects of caffeine and pentoxifylline on aromatic antibiotics, suggesting a potential role in enhancing antibiotic efficacy, which falls under the category of New Treatments.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34516580
Procesando filas 50 a 59

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the in-vitro activity of several new or comparative antimicrobial agents, including cefiderocol, cefepime/zidebactam, cefepime/enmetazobactam, omadacycline, and eravacycline, against carbapenem-nonsusceptible Enterobacterales. This focus on new treatments aligns with category 2.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 60 a 69

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses ceftriaxone resistance in Neisseria gonorrhoeae, which falls under the category of multiresistance bacteria stains report. It does not discuss new treatments or immunization.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 28931240
Procesando filas 70 a 79

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper does not discuss multiresistance bacteria stains report, new treatments, nor immunization. Instead, it focuses on the prevalence and dominance of specific variants of Chlamydia trachomatis L serovars in the U.S.A.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 26089520
Procesando filas 80 a 89

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a potential new treatment for Neisseria gonorrhoeae infections, focusing on the use of the C4BP-IgM protein as a therapeutic approach.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 90 a 99

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses the characterization of azithromycin-resistant Neisseria gonorrhoeae, which falls under the category of multidrug-resistant bacteria stains.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 24378136
Procesando filas 100 a 109

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the contribution of certain substitutions and beta-lactamases to cefotaxime resistance in Haemophilus influenzae and Haemophilus parainfluenzae, which falls under the category of multidrug resistance bacterial strains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 22290151
Procesando filas 110 a 119

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : list index out of range en el id 27199987
Procesando filas 120 a 129

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' "The paper discusses the potential probiotic properties of Lactiplantibacillus plantarum strains, which can be considered as a new treatment approach against Gardnerella vaginalis and Neisseria gonorrhoeae"' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 22387629
Procesando filas 130 a 139

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper does not discuss multiresistance bacteria stains report, new treatments, nor immunization. Instead, it focuses on the biofilm production and severity of Non-typeable Haemophilus influenzae in lower respiratory tract infections in a tertiary hospital in Mexico.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 25585061
Procesando filas 140 a 149

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a new antimicrobial nor-friedelane-type triterpenoid and other constituents from Plectranthus glandulosus Hook. f. (Lamiaceae), which falls under the category of new treatments.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 29370373
Procesando filas 150 a 159

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses the antibiotic susceptibility of Neisseria gonorrhoeae isolates, which implies the investigation of multiresistance bacteria stains.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34106809
Procesando filas 160 a 169

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the antimicrobial susceptibility of Gram-negative bacteria to polymyxin B and other comparators, which is directly related to the multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 35174771
Procesando filas 170 a 179

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses antibiotic resistance in Neisseria cinerea and Neisseria gonorrhoeae, which falls under the category of multidrug-resistant bacteria.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 26657117
Procesando filas 180 a 189

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses Bezlotoxumab, a new treatment for preventing recurrent Clostridioides difficile Infection, which falls under the category of "New Treatments"'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 25734538
Procesando filas 190 a 199

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses antimicrobial resistance, which is a characteristic of multiresistance bacteria stains.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 200 a 209

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : list index out of range en el id 24602605
Procesando filas 210 a 219

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the prevalence of insertion sequence elements in plasmids relating to mgrB gene disruption causing colistin resistance in Klebsiella pneumoniae, which falls under the category of multidrug-resistant bacteria.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 35208876
Procesando filas 220 a 229

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a case of multidrug-resistant Neisseria gonorrhoeae, which falls under the category of multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 30412586
Procesando filas 230 a 239

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the biochemical properties of an enzyme in Chlamydia trachomatis, but it does not involve multiresistance bacteria stains report, new treatments, or immunization.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34655187
Procesando filas 240 a 249

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the preventive effects of long-term intake of plant oils with different linoleic acid/alpha-linolenic acid ratios on acute colitis in a mouse model, which can be categorized as a new treatment.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 25138290
Procesando filas 250 a 259

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : list index out of range en el id 35687548
Procesando filas 260 a 269

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a comparison of in vitro activities of plazomicin and other aminoglycosides against clinical isolates of Klebsiella pneumoniae and Escherichia coli, which falls under the category of new treatments.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 24778450
Procesando filas 270 a 279

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the evaluation of Piperacillin-Tazobactam for antibiotic prophylaxis in traumatic Grade III open fractures, which falls under the category of new treatments.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 25916538
Procesando filas 280 a 289

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses antimicrobial resistance in Gram-negative bacterial bloodstream infections, which falls under the category of multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 31681305
Procesando filas 290 a 299

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a novel peptide mimetic, Brilacidin (PMX30063), which can be classified as a new treatment for ocular anti-infective purposes.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34744743
Procesando filas 300 a 309

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses the resistance of Neisseria gonorrhoeae, which implies a report on multiresistance bacteria stains.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 310 a 319

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses the antimicrobial susceptibility of Neisseria gonorrhoeae, which is a form of multiresistance bacteria stain report. It does not mention new treatments or immunization.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 320 a 329

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : list index out of range en el id 27577587
Procesando filas 330 a 339

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the development and evaluation of a new treatment for otitis media, specifically using cefuroxime axetil-loaded bioadhesive nanoparticles to treat Haemophilus influenzae-induced otitis media.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 22431650
Procesando filas 340 a 349

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a new treatment approach for multidrug-resistant Klebsiella pneumoniae using a bacteriophage-polymyxin combination.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 22846397
Procesando filas 350 a 359

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : list index out of range en el id 25077421
Procesando filas 360 a 369

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract does not discuss multiresistance bacteria stains report, new treatments, nor immunization. Instead, it focuses on the bacterial spectrum and antimicrobial susceptibility patterns in acquired and congenital lacrimal duct stenosis.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 370 a 379

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a budget impact analysis of a new treatment (bezlotoxumab) compared to standard of care antibiotics for patients at high risk of CDI recurrence.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 380 a 389

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses bacterial resistance, which falls under the category of multiresistance bacteria stains report. It does not mention new treatments or immunization.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 390 a 399

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a new treatment using supplementation with exogenous catalase from Penicillium notatum in the diet to ameliorate lipopolysaccharide-induced intestinal oxidative damage in weaned pigs.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 35601864
Procesando filas 400 a 409

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a new treatment, Meropenem-Vaborbactam, used as salvage therapy for ceftazidime-avibactam- and cefiderocol-resistant ST-512 Klebsiella pneumoniae-producing KPC-31, a D179Y variant of KPC-3.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 33167045
Procesando filas 410 a 419

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '  The paper discusses recent progress in Shigella and Burkholderia pseudomallei vaccines, which aligns with the description of category 3, Immunization, as it involves directly stimulating the immune system to generate immunological memory against these pathogens.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34997046
Procesando filas 420 a 429

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses Carbapenem-Resistant Gram-Negative Bacilli, a type of multiresistance bacteria, and the study of a method for their detection, which falls under the category of Multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 25957906
Procesando filas 430 a 439

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the activity of a new fluoroquinolone, JNJ-Q2, against Neisseria gonorrhoeae, including ciprofloxacin-resistant strains, indicating a potential new treatment.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 29373697
Procesando filas 440 a 449

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' "The paper discusses the emergence of Klebsiella pneumoniae ST307, a multidrug-resistant bacteria strain, in paediatric patients at Shenzhen Children's Hospital, China. It reports the co-production of CTX-M with SHV and KPC, which are antibiotic resistance genes."' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 28381402
Procesando filas 450 a 459

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the isolation and sequencing of a lytic bacteriophage, vB_Kpn_3, which is a potential new treatment against multidrug-resistant Klebsiella pneumoniae.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 460 a 469

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses the characterization of high-level azithromycin-resistant Neisseria gonorrhoeae cases, which falls under the category of multidrug-resistant bacteria stains.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 26182813
Procesando filas 470 a 479

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a new treatment for Neisseria gonorrhoeae infections, specifically the use of a Dithiazoline, in the context of mixed infections with Lactobacillus gasseri.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 35877653
Procesando filas 480 a 489

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the evaluation of the activity of a specific antibiotic, ertapenem, against gonococcal isolates with varying susceptibilities to another antibiotic, cefixime. This suggests a focus on exploring new or existing treatments for bacterial infections.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 490 a 499

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' "The paper discusses treatment failures with cephalosporin monotherapy for gonorrhea, indicating a report on multiresistance bacteria stains."' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 28232214
Procesando filas 500 a 509

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses the evaluation of antibiotic synergy for carbapenem-resistant Klebsiella pneumoniae clinical isolates, which falls under the category of multidrug-resistant bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34838814
Procesando filas 510 a 519

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a new treatment method for multidrug-resistant Klebsiella pneumoniae using Echinacea angustifolia extract encapsulated in niosomes, which enhances its antibacterial activity.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 27632642
Procesando filas 520 a 529

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses betalaktamresistens (beta-lactam resistance) in Haemophilus influenzae, which falls under the category of multidrug-resistant bacteria.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34775292
Procesando filas 530 a 539

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the isolation and antimicrobial susceptibility test of Klebsiella from the gut of bees, which falls under the category of multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34374425
Procesando filas 540 a 549

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : list index out of range en el id 24711617
Procesando filas 550 a 559

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the potential antibacterial efficacy of garlic extract on specific bacterial strains, which falls under the category of new treatments.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 560 a 569

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses antimicrobial resistance in Neisseria gonorrhoeae, which falls under the category of multiresistance bacteria stains.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 22700700
Procesando filas 570 a 579

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the promotion of horizontal transfer of plasmid-borne resistance genes from one bacterial species to another under subinhibitory antibiotic concentrations. It does not report on multiresistance bacteria stains, new treatments, or immunization.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 27638011
Procesando filas 580 a 589

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the Development of 1,2,4-Oxadiazole Antimicrobial Agents, which falls under the category of New Treatments.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 590 a 599

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' "The paper discusses the in vitro activity of gentamicin against Neisseria gonorrhoeae and proposes tentative interpretation criteria for the CLSI and calibrated dichotomous sensitivity disc diffusion methods. It does not involve multiresistance bacteria stains report, new treatments, or immunization."' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 600 a 609

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the antibacterial activity of ceramide and ceramide analogs, which implies a potential new treatment against pathogenic Neisseria.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34458118
Procesando filas 610 a 619

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses Ceftazidime/Avibactam-Resistant Klebsiella pneumoniae subsp. pneumoniae isolates, which falls under the category of multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 27636704
Procesando filas 620 a 629

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses bacteriocins, which are substances produced by bacteria that inhibit the growth of other bacteria. This could potentially be used as a new treatment against harmful bacteria.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 630 a 639

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : list index out of range en el id 33605846
Procesando filas 640 a 649

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses extensive drug-resistance in strains of Escherichia coli and Klebsiella pneumoniae, which falls under the category of multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 23045619
Procesando filas 650 a 659

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses the Australian Gonococcal Surveillance Programme, which involves monitoring and reporting on gonococcal strains, including those that may be antibiotic resistant. This falls under the category of multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 660 a 669

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : list index out of range en el id 28571504
Procesando filas 670 a 679

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses antimicrobial drug resistance in Shigella and Nontyphoidal Salmonella, which falls under the category of multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 28106821
Procesando filas 680 a 689

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a novel DNA Gyrase Inhibitor, ETX0914 (AZD0914), which suggests the introduction of a new treatment for Multidrug-Resistant Neisseria gonorrhoeae.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34729712
Procesando filas 690 a 699

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses Levonadifloxacin, a Novel Broad-Spectrum Anti-MRSA Benzoquinolizine Quinolone Agent, which implies a new treatment for MRSA infections.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 27895130
Procesando filas 700 a 709

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the comparison of plasma and intrapulmonary concentrations of a drug named Nafithromycin (WCK 4873) in healthy adult subjects, which falls under the category of new treatments.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 31690678
Procesando filas 710 a 719

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the in vitro activity of Lefamulin, a new antibiotic, against sexually transmitted bacterial pathogens, indicating a potential for new treatments.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 28893203
Procesando filas 720 a 729

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the dynamics of antimicrobial resistance in Chilean Shigella sonnei strains, which falls under the category of multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 730 a 739

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract of the paper focuses on the prevalence of Neisseria gonorrhoeae in Western Iran, which does not discuss multiresistance bacteria stains report, new treatments, or immunization.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 24074904
Procesando filas 740 a 749

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses determining antimicrobial resistance profiles of Neisseria gonorrhoeae, which falls under the category of multiresistance bacteria stains report. It does not discuss new treatments or immunization.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 22337104
Procesando filas 750 a 759

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the high prevalence of antimicrobial resistance in Klebsiella pneumoniae isolates, which falls under the category of multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 760 a 769

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a new treatment approach using phages to decolonize carbapenem-resistant Klebsiella pneumoniae from the intestinal microbiota of model mice, indicating a potential new treatment.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 23250301
Procesando filas 770 a 779

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper does not discuss multiresistance bacteria stains report, new treatments, nor immunization. Instead, it explores the potential implications of intensive screening for gonorrhea/chlamydia in preexposure prophylaxis cohorts, drawing on historical lessons from a mass treatment campaign in Greenland.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 23741420
Procesando filas 780 a 789

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the in vitro activity of tigecycline alone and in combination with other antimicrobials against clinical Neisseria gonorrhoeae isolates, which aligns with the category of "New Treatments" as it explores potential new therapeutic options.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 29803329
Procesando filas 790 a 799

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the resistance of Nontypeable Haemophilus influenzae to oxidative killing, which can be interpreted as a form of multidrug resistance, as oxidative killing is a common antibacterial mechanism.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 33739419
Procesando filas 800 a 809

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a novel combination of colistin-EDTA for the treatment of colistin-resistant Klebsiella pneumoniae catheter-related biofilm infections, which falls under the category of New Treatments.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 25550774
Procesando filas 810 a 819

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper focuses on the genetic characterisation of colistin resistant Klebsiella pneumoniae clinical isolates, which falls under the category of multidrug resistance bacteria stains report. It does not discuss new treatments or immunization.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 820 a 829

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the antimicrobial activity of Ceftolozane-Tazobactam, which can be categorized as a new treatment against Haemophilus influenzae clinical isolates.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 24585717
Procesando filas 830 a 839

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the emergence of a Neisseria gonorrhoeae clade with reduced susceptibility to extended-spectrum cephalosporins, which falls under the category of multidrug-resistant bacteria.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 840 a 849

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses the increasing resistance of gonorrhoea to ceftriaxone, a type of antibiotic, which falls under the category of multidrug-resistant bacteria.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34893342
Procesando filas 850 a 859

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' "The paper discusses Gonococcal MtrE and its surface-expressed Loop 2 as immunogenic, meaning they stimulate an immune response. This directly aligns with the description of category 3, Immunization."' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 860 a 869

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the spread of carbapenem-resistant Klebsiella pneumoniae, which falls under the category of multidrug-resistant bacteria.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 870 a 879

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a Phase 2 Trial of a new treatment, Solithromycin, for Uncomplicated Gonorrhea.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34489875
Procesando filas 880 a 889

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses Lactobacillus crispatus as a potential inhibitor of Chlamydia trachomatis, which can be interpreted as a new treatment approach.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34362705
Procesando filas 890 a 899

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' "The paper is about the characterization of a newly isolated lytic phage Sfk20 infecting Shigella flexneri, Shigella sonnei, and Shigella dysenteriae1. It does not discuss multiresistance bacteria stains report, new treatments, or immunization."' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 27894718
Procesando filas 900 a 909

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the bactericidal effect of a protein on Neisseria gonorrhoeae, but it does not mention multiresistance bacteria stains, new treatments, or immunization.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 23738030
Procesando filas 910 a 919

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the identification of Hypervirulent Carbapenem-Resistant Klebsiella pneumoniae, a type of multidrug-resistant bacteria, using aerobactin and RmpA2 as markers, which falls under the category of "Multiresistance bacteria stains report."'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34556364
Procesando filas 920 a 929

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a new potential treatment for microbial infections, specifically the use of antimicrobial blue light to inactivate microbial isolates in biofilms.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 930 a 939

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the development of Cobalt-Doped Zinc Oxide Cylindrical Microcrystals, which have enhanced optical and antibacterial activity, suggesting a new treatment.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 28367885
Procesando filas 940 a 949

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses surveillance of gonococcal antimicrobial susceptibility, which involves monitoring and reporting the emergence of antimicrobial resistance in gonococcal strains, a topic directly related to multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34780275
Procesando filas 950 a 959

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' "The paper discusses a multiresistance bacteria stain report, specifically the emergence of a new strain of carbapenem-resistant Klebsiella pneumoniae (CRKP) in a hospital setting."' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 960 a 969

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the antibacterial activity of different honey samples, which implies a potential new treatment approach.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 36071818
Procesando filas 970 a 979

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The abstract discusses changes in the resistance pattern of specific bacteria strains, which falls under the category of multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34516780
Procesando filas 980 a 989

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : list index out of range en el id 34593069
Procesando filas 990 a 999

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : list index out of range en el id 30957153
Procesando filas 1000 a 1009

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the evolution and dissemination of Neisseria gonorrhoeae strains, which involves the development of resistance to multiple antibiotics, specifically ciprofloxacin and azithromycin. Therefore, it falls under the category of Multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 1010 a 1019

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the antimicrobial activity of 1,8-cineol, a compound that could potentially be used as a new treatment against carbapenemase-producing Klebsiella pneumoniae.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 26656797
Procesando filas 1020 a 1029

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the fitness cost or benefit of fluoroquinolone resistance in Neisseria gonorrhoeae, which does not fall under the categories of multiresistance bacteria stains report, new treatments, or immunization.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 24203572
Procesando filas 1030 a 1039

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the dissemination of plasmid-mediated carbapenem and colistin resistance, which falls under the category of multidrug-resistant bacteria.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 26093673
Procesando filas 1040 a 1049

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The Australian Gonococcal Surveillance Programme Annual Report, 2019' discusses the surveillance of gonococcal isolates, which involves monitoring antibiotic resistance. This aligns with the description of category 1, a multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 36578495
Procesando filas 1050 a 1059

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the impact of intermittent preventive treatment in pregnancy with azithromycin-containing regimens, which implies a potential new treatment approach.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34699934
Procesando filas 1060 a 1069

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the genomic epidemiology of gonococcal resistance to extended-spectrum cephalosporins, macrolides, and fluoroquinolones, which falls under the category of multidrug-resistant bacteria.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 29324629
Procesando filas 1070 a 1079

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' "The paper discusses a new treatment for ulcerative colitis in rats using Lactobacillus acidophilus and HKL Suspension, which alleviates the condition by regulating gut microbiota, suppressing TLR9, and promoting metabolism."' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 34388671
Procesando filas 1080 a 1089

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper reports on the prevalence of specific strains of Klebsiella Pneumoniae that are resistant to Carbapenem and Colistin, which falls under the category of Multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 27076145
Procesando filas 1090 a 1099

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' "The paper reports on the multidrug-resistant bacteria stain Klebsiella pneumoniae ST11, discussing its novel mutations and increasing carbapenem resistance."' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 1100 a 1109

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper conducts a genetic analysis and characterization of multidrug-resistant Klebsiella pneumoniae, which falls under the category of multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 1110 a 1119

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the increasing incidence of high-level tetracycline-resistant Neisseria gonorrhoeae, which falls under the category of multiresistance bacteria stains report.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 30239814
Procesando filas 1120 a 1129

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses the characterization of Arsenic-Resistant Klebsiella pneumoniae RnASA11, which falls under the category of multidrug-resistant bacteria. Therefore, it can be classified under category 1.'' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Se corto el proceso del LLM por este motivo : list index out of range en el id 26501198
Procesando filas 1130 a 1139

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' 'The paper discusses a new antimicrobial, DIS-73285, which has high in vitro activity against MDR and XDR Neisseria gonorrhoeae, indicating a new treatment.' ' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[pmid,["ai_label","ai_summary"]] = response[0] , response[1]

Procesando filas 1140 a 1149

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_22668\3859912656.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  '3) Immunization']].applymap(_transformacion_binario_val)

Se corto el proceso del LLM por este motivo : list index out of range en el id 36312943
Shape final: (584, 8)

,Title,Abstract,1) Antimicrobial Resistance stain,2) New treatment,3) Immunization,Human_summary,ai_label,ai_summary
PMID,,,,,,,,
34485172,Pharmacokinetics and Pharmacodynamics of a Nov...,Phage therapy is one of the most promising alt...,1,1,0,Phage øKp_Pokalde_002 is a potent therapeutic ...,2,'The paper discusses a novel virulent Klebsie...
34228538,Enhanced Antibacterial Activity of Repurposed ...,Klebsiella pneumoniae is an opportunistic Gram...,1,1,0,A lytic phage-mitomycin C combination was effe...,2,'The paper discusses an enhanced antibacteria...
34199531,Dehydroabietic Acid Microencapsulation Potenti...,The antimicrobial activity of dehydroabietic a...,0,1,0,The obtained results indicate that DHA is a pr...,2,'The paper discusses the potential of Dehydro...
35663465,Airway Epithelial Cells Differentially Adapt T...,Background: Pneumonia is often elicited by bac...,0,0,0,Study of type-2-alveolar-epithelial-cells inmu...,4,'The paper does not discuss multiresistance b...
30266769,Human Factor H Domains 6 and 7 Fused to IgG1 F...,Novel therapeutics against multidrug-resistant...,0,1,0,Human Factor H Domains 6 and 7 Fused to IgG1 F...,2,'The paper discusses a new immunotherapeutic ...

### 5) Evaluar

In [67]:
evaluacion_score(df_Cta)

values=[1 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion3
values=[1 1 0]
ai_opcion0
values=[0 1 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion3
values=[0 1 0]
ai_opcion3
values=[0 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[0 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion1
values=[0 0 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[0 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion0
values=[0 0 0]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion0
values=[0 1 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion3
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 0 1]
ai_opcion2
values=[1 0 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 1 0]
ai_opcion1
values=[0 0 1]
ai_opcion2
values=[0 1 1]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[0 0 1]
ai_opcion2
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[1 1 0]
ai_opcion0
values=[0 1 0]
ai_opcion1
values=[0 1 0]
ai_opcion1
values=[1 0 0]
ai_opcion0
values=[0 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion3
values=[1 0 0]
ai_opcion0
values=[1 0 0]
ai_opcion0
values=[0 1 0]
ai_opcion1

0.8287671232876712

# 6) Limpieza de Df

In [69]:
columns_excluded = ['1) Antimicrobial Resistance stain', 
                    '2) New treatment', 
                    '3) Immunization', 
                    'Abstract', 
                    'Human_summary'
                    ]

In [70]:
df_clean= df_Cta.drop(columns= columns_excluded)

In [71]:
df_clean

,Title,ai_label,ai_summary
PMID,,,
34485172,Pharmacokinetics and Pharmacodynamics of a Nov...,2,'The paper discusses a novel virulent Klebsie...
34228538,Enhanced Antibacterial Activity of Repurposed ...,2,'The paper discusses an enhanced antibacteria...
34199531,Dehydroabietic Acid Microencapsulation Potenti...,2,'The paper discusses the potential of Dehydro...
35663465,Airway Epithelial Cells Differentially Adapt T...,4,'The paper does not discuss multiresistance b...
30266769,Human Factor H Domains 6 and 7 Fused to IgG1 F...,2,'The paper discusses a new immunotherapeutic ...
...,...,...,...
35633723,Identification and Comparative Genomic Analysi...,4,'The paper focuses on the identification and ...
34958740,Whole-genome analysis of haemophilus influenza...,4,'The abstract does not discuss multiresistanc...
26700635,Outbreak of a beta-lactam resistant non-typeab...,1,'The abstract discusses a specific strain of ...
36605851,Evidence of Sharing of Carbapenem-Resistant Kl...,1,'The paper's abstract discusses the sharing o...
36168487,Initial vancomycin versus metronidazole for th...,2,'The paper discusses a comparison of two trea...

# EDA

In [72]:
print("Se analizaron ", df_clean.shape[0], " papers.")

Se analizaron  584  papers.

#### AI Label:

1) Antimicrobial Resistance stain
2) New treatment
3) Immunization
4) None

In [73]:
df_clean['ai_label'].value_counts()

ai_label
1    271
2    215
4     73
3     25
Name: count, dtype: int64